apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: system
  source:
    repoURL: https://traefik.github.io/charts
    targetRevision: 37.0.0
    chart: traefik
    helm:
      values: |
        service:
          enabled: true
          type: LoadBalancer
