# ENCRYPT WITH: sops --encrypt --in-place cloudflare-secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:8Xni6f7oWBi4kSipCmJ0fmIS/ArfW1LhCmA+lpLBfS1k0U+aMAdKb44uMKDEW62MVWTgx2c=,iv:cp7MBqamimdBDKLZ4LG66IIeKI1Gm6G6LcV4N9Dx75k=,tag:S2eAsUkRZhKyaasvjzvTXA==,type:str]
sops:
    age:
        - recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUGs3TWFJM1NDeUhBK2xI
            aTY2V3ZMWER0RlNBaGFIYURocldEaHNhNzJvCjJGRXl2QzR4Q1pXU3lPNDZKWXFu
            cmZzWGxDQzFjZUtYdjVwY3NMKzQzMHMKLS0tIGkrOThnNDVYc3VxTHpMWTUrUld5
            eDhvSFBaRVU2NHA3S3hjZHVta0VjRlEKrX6gWmBx2Tm4iCJHEXwWf5K7mBXIu5ou
            pyELjqM8+a/RBfSVYZQy5ILdMs4t4jWCCKfSDkQOrl2fh/GfIH8VeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T13:56:59Z"
    mac: ENC[AES256_GCM,data:a855Ay1JU4oPGgGczNwStE8lFee8LPf78cPLzXlbp+EJoB6Qmoef7yNgTFssOP0YvDQRIke2Fj4yE0WBa+ro/QALHLz7RBFg7lAJxJKKtnanwiGHC4t2sVHf3H7nlbS3Jk5djgjd8Ic9j3rmLyouj0aDy45+xfAUyR33oRPxoIQ=,iv:35B9SZ3J4dRdoxf1QW+wO6dRZLIfZw9kHyYcl6LV26c=,tag:m7Kl+vKn2l3qhk3Gwnrp/w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
