# ENCRYPT WITH: sops --encrypt --in-place 12-secret.sops.yaml
# sops will use the .sops.yaml config in the repo root if present, or specify --gcp-kms
apiVersion: v1
kind: Secret
metadata:
    name: dockerhub-pull
    namespace: portfolio
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:HP+4yW826E3+9Z0RFxkU9p5GI3M3Jokx6nFFU4ndmTBT9Tmj/wPn2u+95O3x7hpKMpp3pYIpwV0pYVw7VQHCTAzsaizT2G7/cgfUFfeMWKw21pK6Q6SPbk+ncFA6/znkbLRo+sAnb2HHZMMUF2bld2vsKWlQqTf17sggUUzRj2QPe/ZWN/Tdy41xl1KvaajKAaWXzGQ/Q0/aC5gS5DLjfVs5+4+15jn2FJE9Gh6WRvPsWHhTSBnXdmur3FVkqea9,iv:Casgaak+X+00rOhzDOFl+JqdkreSiXjIxR2o/QDqmTY=,tag:BmbQOqxMLbJQYp92uShzVQ==,type:str]
sops:
    age:
        - recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuNW5qL2Nad1Y5c1ltcWh1
            dldTcDZrVUx0TFl0S2VhS2Y0Um56dGtVN0hnCnpLYW9kakpCclZoR2pSbE9VZWpS
            eXJJSzNhWDZPeDV0bWRSV0VORVB6Mk0KLS0tIGxhREVvWUpqNTRnbjBKZzAySUJj
            ek9Dd2RrZ2tLTGFqZUZ6K3NranVSTG8KEh6Di94MBSmKXMyY1ulIgRfvAwPKvmjU
            U76Fsm+bup19hw6gPbQ1GcE2B3N8DSYyAq9lXJh/FpT7pyi+jaS/Qg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T13:05:56Z"
    mac: ENC[AES256_GCM,data:gOZ6tqBOBxa1E2oAorW2uSn5lMz8MUBvsVTfrjblzdja+BZ9y+i8HJqjF2mmvs+O5Y+D+/Js/UYBnlKTvBRWdxoAm/q2H0Dy7xwGS90FAAT1tq4/wgGZEIGb7/JoHeLa8axrhMhc3jkHqCy/w0Meoaa9aHuQDV+2PSlWaPaoNB0=,iv:4Zo1OUwj8vfNUf3lp/VlesYhU2SkMRJgQIoak/ARse4=,tag:rfMar3phf9wju1YT4zPW6A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
