apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 10-placement-rebalance-rbac.yaml
  - 20-placement-rebalance-cronjob.yaml

configMapGenerator:
  - name: placement-rebalance
    namespace: kube-system
    files:
      - placement-rebalance.sh

images:
  - name: docker.io/alpine/k8s
    newTag: 1.37.1
