apiVersion: v1
kind: Secret
metadata:
    name: repo-cyberhawk-gitops-private
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
stringData:
    type: ENC[AES256_GCM,data:Hfwe,iv:d4F1ubthpCw4XAN3xKkGkU2vIDyq1mOfUAc7tdc1Ih8=,tag:VHvJtiezcuuzovR8Fu2TLQ==,type:str]
    url: ENC[AES256_GCM,data:adfmAswfTqOXv1bimNQ3LOaUy9JtuEx1XiGbts7ye6oH4K3u+YSJVBiGvl1oWAoQC3Tdx2Al4S5rG8q7jy38,iv:HUBDw17x7gcvDXakKigIw1G4Y3EtJ9CfWpzJpoQjv/g=,tag:s4vk930mx0l9r9PW9hhJgQ==,type:str]
    username: ENC[AES256_GCM,data:0kSLxc4X,iv:A7mjIJVTfO3inYhiPYVuO9P1u0GKN3nxX/eLLY4WXYM=,tag:eWQ4cMOI2qgwhZD4stDx2A==,type:str]
    password: ENC[AES256_GCM,data:0vi8keMY2PcJG7zXrVmUQUKs0py5GAsPApdi5/RrHKgUp7muhxTHkg==,iv:YQpWJESN2A1G+3e4kkaB7bCXqchJrNxW5QjfYgLXPB0=,tag:AN+ggxtiuZri1+JIgptfRg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQ0xJTWI1ZTIraEJIdkl5
            d1EvQ1ZTRURkMnNDTDc2UDE3dTNIakNOVFJVClVMY3dnZmVMdDNEZ0JMcjlJQVJa
            NjNuTEJDZ01uYWI3Y3ppU2FGT0M4eEEKLS0tIGlOY2ZBSXp5RXpJT1BIbVBlVjJv
            VDdQM2hVMVBYUWtGWVR4WFkyTTVCQ2sKlh+vZ10ETKBna/YebIf2v6cVy895ksGN
            3zd9E7NBi0mxfNid1Br+0byejB9L2RpO7XBiLOODfE5GoVQwblPk5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T20:13:23Z"
    mac: ENC[AES256_GCM,data:bfpJk+ul1avOFbVN+NZvykKjI+z1ZHeZnHnvCJRHvllVAvBiBGxqz5PjINcBml72QJ+2x1VFlyKu9ILWiIlGsf7k+EkUnY8uOn+rnhjZ9/RGi+jmq7MnCARjD95EqeihGuPk2P8jg3uoblKsBwDR9JJmg9wTl1252crlRwlqzq0=,iv:FudyNK7Xlj3AM5F5vGFQlHjLYjOEErZLHbyKLKqTvi8=,tag:OvWs1FlVRa7/gnPdBa2Mow==,type:str]
    version: 3.13.3
