apiVersion: v1
kind: Secret
metadata:
    name: repo-cyberhawk-gitops-private
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
stringData:
    type: ENC[AES256_GCM,data:Hfwe,iv:d4F1ubthpCw4XAN3xKkGkU2vIDyq1mOfUAc7tdc1Ih8=,tag:VHvJtiezcuuzovR8Fu2TLQ==,type:str]
    url: ENC[AES256_GCM,data:OdW/1X1WzdO8YD8ctrtyNqE2757UyIr30p4iZlGVhHzvVJruSVW3FnBOVj7x4x+ImLIwC6iKAg==,iv:aDcsx55WhM7gUnhmeA684FEBi8XfBLE7G1lTkP54oH4=,tag:5zCrR3ZrvHEZDvxsqjRcqg==,type:str]
    sshPrivateKey: ENC[AES256_GCM,data:KEDvdd3sFpuWa1UloZb265miP85r7pEh06EvrUQa0Sn3aVxKCz3n/XbkkHyCxOvikjcrqnHnu1TNFFwSt5YTioIBHdDkn0qVWNWAMgqA+CDm2WvJix2LDoIeM624e6fM92oyK8x32uB0w9rkgdeLSMrqyQSxhyzZ5527DAmRVQ4BXVeK/x/CcDBac4LMBmiW+HYUo3dmnEtysvOA22VswiguG/iUqAJctNmMoWhnrdnz/aX5Y2zb51zs+8pZpE4bhiO2ogl8yqdNo5W4C7OvIty/CNj9ybw/MrlCA/8mj2aoqzm/g3ylTUHvMgISp2j8TFcGbVv78pMXh+mY6HU93Nh7SH42o5kgpJxkWmpJjv6P3l7S+2yjA0YSLSRgeDIOtB3zP23GqNc6ajsfm/TvxU1ltR06Th+Ztm95ELlVx+L48gyoIhIutrYwTMyn18+1i9XanBZgaI3mGYc0Y/djHMc0WkrvtAf4kXrSqo9ES45CKNzWEZhNxRPQKftMmaiVp7HoCP9TJYbFdTITkDrc71NEhzHQdrY6KERPRaCSGAmpO/E=,iv:kBQFFChMBm6BRAS82rz32htXrHI7raGUMrHfPSrlSIE=,tag:v05Aiv4T2uEBFXPgVk0fLQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQ0xJTWI1ZTIraEJIdkl5
            d1EvQ1ZTRURkMnNDTDc2UDE3dTNIakNOVFJVClVMY3dnZmVMdDNEZ0JMcjlJQVJa
            NjNuTEJDZ01uYWI3Y3ppU2FGT0M4eEEKLS0tIGlOY2ZBSXp5RXpJT1BIbVBlVjJv
            VDdQM2hVMVBYUWtGWVR4WFkyTTVCQ2sKlh+vZ10ETKBna/YebIf2v6cVy895ksGN
            3zd9E7NBi0mxfNid1Br+0byejB9L2RpO7XBiLOODfE5GoVQwblPk5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T06:26:14Z"
    mac: ENC[AES256_GCM,data:bYJHbjiW4jBsZENERK+HT6bBvFP3b0pU1EjJBodn9ROhKektuxfyUVbg9TWdXSo0aCgwmXzHjshYOfiivP+aRCr8o6GWqUbHXDzCyHyPxmcO4PzgnJdu0ZCX3zgWxA5fyG5Lj3TD/LG7yq1ot6ja1DNatMr2eC93Xj75sPCMaN4=,iv:Jb/ForSAeHXRramfdJ4nleogHr/vaaDJ7dKTvVOW3iI=,tag:gvYXPDMrlkfRFWrqUUAN8g==,type:str]
    version: 3.13.3
