apiVersion: v1
kind: Secret
metadata:
    name: democratic-csi-files-config
    namespace: kube-system
type: Opaque
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:LYSNEttj4O6JaqyfM/D15Ligd6zi4XaIIBFBePfKumT8jvc6YIzq67sSy0JwnRCBg5DLXArd4lrWYKXEtlvFVbOCP4Atnm3D832LCboPw3pmIqhBsV7LnOLNJy/ZwnjpwrQZV9MGumUm5D/vaeK++JFuseY74m+pIR0h4DGdNaLVoo5WjOrpOOPWL70oKJSfkrqW82cp26m/MuLmKt4W4QxGsr4lXtGSXcqQz42xCxEo+KMs8Lk6aUzJS6wpP/gpj5DrdRceAHzo3eWxvXG77AfqYxR1ZevsTD+yekVpFdAucMzPaqg68K92h++9PYJGUKmOBbj2uLGjEV0t8tPBAH1CbCgC+Ow1sHknviOcNPa66n+BND/YHFGwyUNg/j8fuAyOtSyighW1chtw0oBLJewRIktggxMrJRU0+gVbWHai4RZbUA4Xk4TzeoNrLnqi0YAI6zNgbW6v2RCTMfx2B+VEv6GXap6FZP+SQpcuSN04ARcJyNIbnZf6QHhw2djKjMKbYZFdPg9C1LJjpinkiwqMqEDIcpjLJa3rq+G1DZcVHFhBah/lF0VJF9BHVLcpgcEBm/nM7KRKIHCZHBiCc6XOFhQi0w1YsIj8855etir3AuFtu17g6LHIUlrWF5MCjJoXuHJTGo5oJFQQ7R2w6Z46eFFVoGpp3vm7wF5Jeb45u8iu/AqZzkk4CXPE5D1kE5Urp4c/C7aBVrEPtbZZUdbc9HJuius6ti9a12jFoV6kX4T3Pl+puYj6nerePczRFDMtYhWO7yhSWWdAd86AViZaWkPPhMIFhKgum1n/Xxxruh5QOzhcTqbjYIfNMyM3GbU6CxFYvLWthhvpcNvKBIhoF8Np9RO6uZotwZz8I+AFQQ8EEV8MHDUg6zVDzigzEhzf4oZGmZdczX2Gh36+QSC7CgXOVpYxn3HQdru06W9OAPOf6kMefD4FVR2qUFA/FOPvVtfINHG/p40VJlxHi5z4hweCbfOZ9ylKXnxJcjwzNHfXAswejCyIcuTYYOyC2icZQd6npVIPNrjIMJjoYtsC4i0XgyApwN6Wbs/SJEJKRiLM3riWkT+6zbmadQ==,iv:+r0KvBVOKF4r4O7hAmYBegOAGNeP386lAT8JGE1vGBE=,tag:oMtN5vwm5jdoCf8xvNb0gw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmOGxiamJ3SWVtcVFkNEgw
            WU9QMHlrRTVlOVR3bEFGZDFkOUI1czdjeUJnCll6Wkk3ZzVodmNlVFNnbGxDY0NL
            U3ljNUovL0MzYmF0VEk3UlNtZTdLNmMKLS0tIE9ZUkRqSjRocFEzZityd3ZtaWhw
            YmFUbGROWGFXVlVVeHlBSE52Q0tNRDgKk1INykmHyG6GOQqERK555HRdh4ofoabm
            TUdMg+brXFPc2G3o89gesRrqnxMZNEwdLxtz638L72TQQnGPxFZPtA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-29T10:29:57Z"
    mac: ENC[AES256_GCM,data:oYQpxKYcTzflVMjD5WjATZ8w32U/MI21Mlk5e2zrDFNegzV05X35PZkYoXWOB5/T4CWVcrEJv54hWlsD9P7Q0aczIxRL/lpw4lYjCRk56bcKLyGLlwX7jwdskacuyY5i5ibdQVnJvm2NT6mlTaB3i1m9FRR8uA/I3SShOiKC61s=,iv:QKZERMqQd0uD9MKc26Plwd5wr9cx6CYp6jtpubyVuKI=,tag:gj4Bi/G9n41NoixWGvUU7w==,type:str]
    version: 3.13.3
