apiVersion: v1
kind: Secret
metadata:
    name: democratic-csi-driver-config
    namespace: kube-system
type: Opaque
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:mDRD7HNcB8r7gwNf6avr7GvmZ8S5q4R1pMUxrwKkZXPkwmytwmF77xoGM8B/euUDKG2FkE+TvQnTWHgh5TRVsZSFGV73i08/emCaBpr+6GYKVN5mYwx53MN9un9X3vGnHVSSNeHy7qCiDq/mk1kS6YKjoSYsaRPB63W9g6FYtg6z1J+ISmBEa7TD57Ynu2p50BepfOATWzrenOHPp7p3tolcMPkxzpEkr+zoe73Cbg9c8Apwzr8lA/4e7FOpMfdYXP/+ewc8WWJzcKVEj5UeEoC0AehvlUIP/oSahmXURzTs03knCxZnjJO/f491qwDwEd+qunD/WRnoPHaM4IczgpMFzipwAB2fO640+gEgVGDn5n/pAiVXTi1gsPrspvJ4dP2SD3uL/oidoa/Kq5+syZzNAK4qFEy5evkxyberEUFr5fTPbts4kIgHTQGzG/TUd6lVqKx6+vNljR2FkW0fVy9hYnuliOzv6HdFIo4ILv2EvWZ6equySouUn4sGprAWNhZRwmkmttPi+rwvDYCfkZ+MUMRoPpzOkHFyWWztSUmHOlH663y//RCZ8NMVbJwUl7aLKik6YG0zYsTyvFpyqbvswlR6wcpqEz7DptIehI8BmDVCy8rT/2xJuJui3VnxwhcxLSrlm3ARpKkgc8BdQiy8qL3TCLBqJG22XLaBWp/wSOvlhqcsQEAJij8xlGwpdF8iZv1mJQoPRf0cXPjv/o1YGSAEzuuc2Bw6x7aTfwq6NXTO86mUBiyd2Al36hZXOP0a6FDRAHB3HYMv/nY/0lLLFNKf+nM/rndjEL86fabLwvSTOox1/dtIRxPY2IWMQj/2Os5LYUMRhxDL6GNQx2FXWpO5g24TmcuDkimKgOp0WegkZ/i0Rq0gOrVTP2F2nASbxTBNtrrEI1jMxzgFE4UZxMHtTJRVbQ7uPUkYT7uL1L4QRfqATaT4Gf/iaKQLWxX4KkUjn/pycM4BSA1Skx4RW5IEPrbAaLDd/hFLD55nWY2Gaf7XN3ZX79/c4DNpc/k0eAAzo1dJtOxrxGUSySToAcj9iB3XJ9bfLAU7Qc3l0BbX6S1PKmQVVYazL5JqSCn7RuC1rba82Q==,iv:P5+YF+GQ3Pg/6WY1a8MFRfDGM4Y6A6NOQ3VQwIKEI3M=,tag:wS3L4qx+NXvwR2I/qiMDTQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMEptSEM2K0I1UG1kc012
            SXVDcjhIZ1N5b08rTm0vRXErdStCY1ZTNUcwCmhvWE1Lb0hJWFF5eUNsNDdwamx5
            VzMrWDFxdTY3d01nTS9DQjZJalZUd3cKLS0tIHBHYzdZRmhMcWxyY2hia1JxTFJo
            dTBZeWtyTGVlREE5aWs3T0F4WER4NFkKcMHM9jvKGzBqgL1L7R0Ic9yDlPgH84Gx
            thKuKRZmfCwtIfI5aPTcYcaGE0IHopTYISfAj/1yR24h6XnhljXuyQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-29T10:47:34Z"
    mac: ENC[AES256_GCM,data:ykdk2Ag5drLKPU0WatX3PafGggcxtO13TqUzJujR25e3HGYXLRX4acCg+C5tPuOJepIx0CtnfG4FmY4D5nzrx/GZYDgQayY6jAZl2rEg0cWkZ090EbpW//X+I16TotIZqoDRKm/ECls7jfbeHbYKDfys915zqlTm8inE1hvY0gY=,iv:OOGXRIyuouG319Ue3HIriiwYUloT6friiygMyarkZnM=,tag:QtVJ4qvKE4YnKHAftDWnyQ==,type:str]
    version: 3.13.3
