apiVersion: v1
kind: Secret
metadata:
    name: democratic-csi-files-config
    namespace: kube-system
type: Opaque
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:PVAsEcCy1daOp2QfRJJgKgQ5qx6fZ4KdKByypFvtbhOOmsDdUlFFFiCGkykcmoE9b1at8H+MiyhIi0APleRVJ57MABlpKBGBsJr1DUWdGLfFCm7qgp1NLqwb43BEu83QcKTsPjdysQM11znHr+FyqV0224GAcTQZouvnvfOD7Th7AyKuUR+nCHkDrzS0RCvfXPQpYSOCCKfNunrlOfWNu7J0ToCWBZj7lFOFhGpB4xddwpO8tkOaFlqe9/zKJYi64eiix+D8+X7j5RRNKK4/Asj09tYUgne9t4SbnmdrPwH7Lu0T/D8OEK/lNuwlEH9ghukY9caIBQUS90n/0AJEhSu0EBCX9pfSxOcm2FuOJchGZjb1ZMoCOPuI3RpeOC6Tiq34jcC2ERct3c92SvVTPknW278+nldH8CvePp5As10CBBjYUZOZipQEuxuhnYikW0ftmSCzkEoQJcxDs+vYEA/W7KNQt0kZVN2sKOhLh/+BJUzPfroGTb68Ssm2nov+9vV12ceicVgmdX6cr52prkgs8MPVu9+xH8amng/xavzQSqJihLeVfNSSYogO+891+3X+JYncY/TQAEAugIv33jzsZ20j+mS5FblqKwNiUYX0ODZArn+px1aDc5gt6JbL4oBr6vUJg2svLSf4tdfT55TItDEO6SRJLJVo+D5CklZzLSypWkzqEr8M+4FUNU3AK9+gdXP7Ei3RptVrMvzVuPKuYJ2iD3YDRj2PPtUsfUthHB1wnG/YsC/qkyASyevi+dHDqMGkUGPe9+lQSeyV4QOfJBqSm2Q46aWsNya2Hn7vtcIlBmwmgvgFy2MNnM/flHOdw6uj8P0BKXqFGK9jxbdew0SxmNIhrJ9jTVMFCyJNOP2lqrIFwaCwHmo8+e08/7NbpVPlyXnOSubCSZmrsPLEmI0Esd84TzNbSxltOYsQYk0kzbQ2K7ys4UhXu8XZHdkaG2GO98uuA0yz6ewUKo+1BYOI5PqJZ4279cEc9gqyf7wsthmbw2e2NmtgzuHqWSJssRwrR12zsvaFWRCca5akoZAK4h4Px9OyD5+JtsHYIFhOFzpuJlK8w/aH1Ho+MTUWq1x4,iv:sb9g1fwX3LYReYiRhP4ONVP5oNEvvtK4UduFmNIwOlg=,tag:rIISWGnO8PXyXD15t4Z15g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmOGxiamJ3SWVtcVFkNEgw
            WU9QMHlrRTVlOVR3bEFGZDFkOUI1czdjeUJnCll6Wkk3ZzVodmNlVFNnbGxDY0NL
            U3ljNUovL0MzYmF0VEk3UlNtZTdLNmMKLS0tIE9ZUkRqSjRocFEzZityd3ZtaWhw
            YmFUbGROWGFXVlVVeHlBSE52Q0tNRDgKk1INykmHyG6GOQqERK555HRdh4ofoabm
            TUdMg+brXFPc2G3o89gesRrqnxMZNEwdLxtz638L72TQQnGPxFZPtA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-29T10:47:34Z"
    mac: ENC[AES256_GCM,data:qphOwOTmH8nJzgS2McZI5cQ5ZTAZW/96HY91b+9Kjkak5CQkj17MRqkmExOYJL9/GY4lBSY6Wo5WCqAEX+hGkWTzulzVLwaJE4ujUhY5/U3WfWGhUcTltUXq5tpUKEOcMA5CSf1BY9LQR97sYIgK3LXGLwiFux1G6ICJytqoOok=,iv:1fDnioCjVxEgMt5J957NEsgak5BFk0kwvVlP5ucVAjo=,tag:di/rivmED5lKnl90xAtNRQ==,type:str]
    version: 3.13.3
