apiVersion: v1
kind: Secret
metadata:
    name: democratic-csi-driver-config
    namespace: kube-system
type: Opaque
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:FjxaAxA4E+YSwTPB9YMkxOolPvYoGlEI1jOafpchf6TsjV8O81YAEQ0H8gytEVsrC0emPr66hX9d8GUC3ySIBA6tLVbTeWjYb2+suDszeIVynQiQ5v8lKqZ9+NhEgpjjEFyiMm98AzSaGvkO2WhT/pLmVebWLCjl3HrDbKi2wDXy6kzBqhTbnKXbriPnkNNd+FM1f+2V3mqjnty+WzY7ibIWF74tc+yIRmvgiIf5fKWKLebnoUPEl972e8mmZsia64M4wcZoNpVnes/iHbiLAuPBgTGDM+S2dUTwQfX4HdcQgmmPoIukqz5ZjsB2wIApQPrU9HxNadUcHrj9rueOdDx6eijhQxg3UMS5aqJP9Xfs1tf35PqTYyN5KyQoLKzZQI6WosdmI4de9K5WS3JQOqenjwr08K5gCktGz3Jsb26oi28S3d17nyD21fUTXaLCESdQd71YvJnI8xsxhzAJFUhXzRmKsyweP5GK334eKl9rpiQ0I8oH+dueSw/mb8qyFz8QIFWe4rqHR//8dH0veoGtqjP+7hDjHfKKs1kjbQHb6ebtOSMW1EFO+x4nCqDhqrSDJTpzdJJTrP7eQrv2ezCDgwF6bxerxzSwW//7RuCRvm7jQb5HnLaDbO3t+YCPlvPb4NStUNA0h+vn1JYHjQqoiWkKmfM1Hpj00rDCEo0XB3k843zNDYHuH/XtYKeV+d1eEfXVsSyNeGNpgSKDFFV4PwCVYpREWQLtOVL+MZe6/ptU5FEG3MG+Pa0nJzXdr0u28WRu4tqDWP9oD7oWrInmGFUFId5QxO2D2UYBavfpW1m0REer++MlRWX/6mAiaRqbqCbqqrNXaUWawv1lhkkVE2vieA7VNaOs/VHYuJYsCVb6Egp2yH6bSFxxkOkzBVt/aK7XPShpbI1WQ2KDytd2TP8IUrv/II6w8l5gEInL+CxYshinxZw+3tAVIQWHytNckqTlDSTU8+6qyTBfWspZo6t1Wy2oK9/idC6SZ1VBS1oDqf8wOLACOKRvf7nESVA0hZT9e9WBTk/9pAvPrSlalIqAKDlnOBpXll2oEtMQXbsrRIGWY5sHZ/TQR0YUziA=,iv:h2q1lQlMYpauIutaenR0CDKEtI7UAF+xyJHoh/CyLt8=,tag:AEoLLXzwnozRtlFFBN5ztw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMEptSEM2K0I1UG1kc012
            SXVDcjhIZ1N5b08rTm0vRXErdStCY1ZTNUcwCmhvWE1Lb0hJWFF5eUNsNDdwamx5
            VzMrWDFxdTY3d01nTS9DQjZJalZUd3cKLS0tIHBHYzdZRmhMcWxyY2hia1JxTFJo
            dTBZeWtyTGVlREE5aWs3T0F4WER4NFkKcMHM9jvKGzBqgL1L7R0Ic9yDlPgH84Gx
            thKuKRZmfCwtIfI5aPTcYcaGE0IHopTYISfAj/1yR24h6XnhljXuyQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-29T10:29:57Z"
    mac: ENC[AES256_GCM,data:AdnjF0EURq2LQ0l7QI8c6gbS/GNMu3ssmE79mfJNdrBvlA1GCqBAO5qnHa0rjfERKwYJR1tS/sSck/VTfNqA7miYy7o3TLRf5/XkEi1DBNOPylLp+r0sHQG/du7ImTswdr0lYUeioxufEWax/rJr68RWhAEXqCq+E6Y38S+OzRo=,iv:dw+DsAd4eRQr6LBpT8KKHHhp1gCxDYvav1ss37WJm18=,tag:EbT5wjg3xE+c7z1NHl51Zw==,type:str]
    version: 3.13.3
