apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: democratic-csi-secret-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - democratic-csi-driver-config.sops.yaml
