apiVersion: v1
kind: Secret
metadata:
    name: netbox-secret
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:Fag/2wBsvGaSMwfNYeCssshO/cSfz9NIdiG0Fe42pq6pT8NXD/S3lxJjPAoKB+n9pe1+zXsCefJxPU5Ti2EHmWjqWOyh4CQ=,iv:1ENgoT9NAKEGadlUbLrOQg9kWBVhQ0dSY/1kpG7Ffjg=,tag:L9u1K1Bm6+mk8pRn8HIs4A==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:MxBPmGigDi02Dy6kg2Epk33wB+rz3e+l6ya1Pq+egXl/TLqM0G/p8/RDhUMPCFMWzxmpgHeP5IGMnQx33J12Lw==,iv:HO+oIMHiQDdafqdUszfRN3gMmyT063nGWuGgm0fStgs=,tag:b7AY5suoTlt58LSLmD/wMA==,type:str]
    SUPERUSER_PASSWORD: ENC[AES256_GCM,data:Gpqdkkgvuu6PmsxsrfCL/f+q9Lv97KwG/TjI/w==,iv:QA9AEXnmX27ad+W7IeC9cu4RoMXkLpCieVInnCrA5Yo=,tag:zqOxHRGBLt+QYaPs8nwZnA==,type:str]
    SUPERUSER_API_TOKEN: ENC[AES256_GCM,data:aQicSIgs+KHR5F8MaH3qANAUqrOKod8di4zvBQQ4jRnFGkEVR09pOQ==,iv:EKZSdk+u3V11wKS9EgsISy1m8gPP9vSJ1/JTNN27vuM=,tag:hWmmh8QiTQ4D5k4xynYyBA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLRDFxTURITGlrM3Nud2RO
            bkRpRUVpejJTQ1JFSVhPbzFFK1BZL2ZBVERBCnZ3T1NXRm5kOXl6OEdTNzQyWFg1
            cHVtOWdsQWN3N3BDUG8rNHFEeG9JdnMKLS0tIFM0ekJQcTliV0s3elFjV2gzNmJl
            bm95VTVIaEFBVFpHci9TMzRpZTdqeG8KZGcEaDSb2MSumLlnZEpmC5Xpe9681RXL
            cZgF2fN7Eu/wFgHjJznz64G04zBJBUam0hPKJJOqMkveYoeAheruwg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T09:18:40Z"
    mac: ENC[AES256_GCM,data:GHu/a71QwK9M/eBpqAWE++V7u8mDunwqBATJQM00CgItLJiUbW6rvvBZ9qzXhzGLZtXRXkZWzhSD9ArqHWtfRmqjnvJhKLFuUUrM131pSyTcfzVAHejCgYpiycLESGUpFCNyDeYbs6XyYD4hSE22UPaaADuutnIQktgPHUo/Mfg=,iv:/pAleFDFx7POPa1ZhdiR2SRIngKG+zkoEQf/SBdjvO0=,tag:PdTePWkSXZ87CJIXbhOXvA==,type:str]
    version: 3.13.3
