apiVersion: v1
kind: Secret
metadata:
    name: netbox-secret
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:JKlaF9pYCi2scRV8eC4X7m1BfIXA9/y5cTVcdJL1pjAllBbu04WqclqZOuBeclCcA8m0Uvtk9AHRLPczPFHFjon9iLokxc4=,iv:RHBXz5YjbkbqQZ8g420jKVaU9ADjx4Y17lpilpdLXWA=,tag:8uV8CKRG+0ZJ85h4zOqu3A==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:29c67LhWbhpvuSmu9HHLcD9WvJPVg+a+8AxdCGRiHB6R2Ai5SueTaJBsIi7/2Fv1JOwBKARzRM8ddP1aknCQSg==,iv:OvQ6diFBY7j6hM1E2pM0sIjmHhWI0O+7t67UBSs1UHo=,tag:wU3HNabNvOYdQi2tuAW/Ow==,type:str]
    SUPERUSER_PASSWORD: ENC[AES256_GCM,data:ojjEj3o7XfIWpIcjFWvuZta3d0QraPk6IUKe6Q==,iv:csNVUq/XRdpMUM95eZ0nqkrJoz6m4Xsr3YpxsGyoBmU=,tag:Fh6+9OThCexHGI/wtMep9w==,type:str]
    SUPERUSER_API_TOKEN: ENC[AES256_GCM,data:2X376R33ILMh05scl6CmURGt2ux5Re58YeAJnJZ4Q/siIeQ2OuPBFg==,iv:gdBZbQFGd0wErvyDz5BoUZhOCyLRdF1stMM2VO6skdA=,tag:RxmiRNOMmcJzzbGY63Fbpw==,type:str]
    API_TOKEN_PEPPER_1: ENC[AES256_GCM,data:L1JLc8q5rJVuzpMHp4W/NLNfuw6LjgdtPaWjNmE8cpLlObVcOszez2urA7Hl0MIx1oek7SfYeceu7+WlYCNxsA==,iv:4hM8T+iaeuOMWTSxmTasOKGGiknFo90207j7vBtg9vM=,tag:P0NlcGsyM6A8bOzK/77BXA==,type:str]
    SUPERUSER_API_KEY: ENC[AES256_GCM,data:gbi47eNFf7JDzeke,iv:+wFR/iKioDZvycHW9ulwRHMxOycK6L5F8ii9bZYmXgE=,tag:8Y4U+rkkwwOvPRfC1B3/sw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWemxyNTFKTnRxVW40Y0dq
            ZlRZdHRwNnNwa0x4YkUzM0lhYit2YjIxSG5nCjZPeW5tRFEybGdVZm5VdlYwN2Vu
            U1ZHcFozcXhML1BqcERoaVRLYmdlYUkKLS0tICtQWStva2NZOFc5UnRtU2xDMXhE
            YzBJVXRWcXVPQzhmN3NtMkJmeUhsVWMKJr4CCyz7N/gpvHS9KuKy4kx3bLHTf+Le
            jvumQZRhjuRfs/wnYbwwvWUFXTlfYXFjNNsc9UAaLMegjGZt7BcSNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T09:52:12Z"
    mac: ENC[AES256_GCM,data:oKSbQsOc0tIwXjPZXj8h9X5zoVW9U1XL/spc86khaXCvuxejflUx8XhFQpqYOrprUBDRiGv+rRkQwdN98kqVPnEWtm2zGPVNpEngVIzvag+r0wF57t2ZrULHIiAtokGIkzN4wr2UNBnyrl2bQ9zADC7L8OUpjhVIrXx2G40ovBo=,iv:PCiZ4nDj6fL7RX7nApggxPWCWDPYptO9O4biVSGDLlo=,tag:t1cpvizrwih0Spwohiu5og==,type:str]
    version: 3.13.3
