apiVersion: v1
kind: Secret
metadata:
    name: netbox-secret
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:JU/Uenow0vJs/u5hbH+xSfRAxCUzKMxHxsRMwSgRWgUxKE6I2RvoHv6w0XoudvkgUHz9R5fogKtUXAhrhmuz0hR/Sf1KCYI=,iv:/rgPB88aBMUUxcuUXk3fiXq6ZAEx73gjeUn8peZvYng=,tag:44sDiHwBhg1FTty4gKGMUg==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:QeOrEn93JVdL3776S3uhxO+KKzfeE4Sa8/Y4wqJncSIx1CjwJoNWfTnntqjxgm64Y+N4twSxjTkad9a93NagAA==,iv:cW706b2xoBTQ5zWSYfyuh8t5jYZidX1Zbnxc3n7K8tw=,tag:TBqVulrIEcBz4UYkB+NA8g==,type:str]
    SUPERUSER_PASSWORD: ENC[AES256_GCM,data:CXP8cegiojbEfyGqv+rsOycHy9X8QUlsYK0F/w==,iv:sgWt0G3pFVn3MmvSusgH2isr5rij06CfHMrHqMkoF9Y=,tag:kpTMI+6NF610zDiUHFIwfQ==,type:str]
    SUPERUSER_API_TOKEN: ENC[AES256_GCM,data:fqa84VblW5o+EciM60zrzyOaqo2FqEd7G3B5co3j9OIJKIvbT1mGEA==,iv:jL3S7yAFY6aDvlvBYrDJ9lFeMjG+5guVvClCfLBNz1c=,tag:e1O50AQwW85z/c/yZ7ZHNQ==,type:str]
    API_TOKEN_PEPPER_1: ENC[AES256_GCM,data:78oVmBhfyMqL/TpknitkjXY5y/788jkHQzAMCHm2GfIs9GkDdqjNA4k9P+Kn3kP7kYeXnCxuaI5/lrjzjSK6kw==,iv:uUc/9g7STEKFuj+rtZxAX9NLbxrt+eB8KfHeL40FZ2c=,tag:TkxLTXQqo7vMmzhPSl5r7A==,type:str]
    SUPERUSER_API_KEY: ENC[AES256_GCM,data:b5WgfrZqxQIy9DBa,iv:id8Dy/8USSQ4kPm0Q1jj17JXTL5WTS4UZ03aEU+CGD8=,tag:CjV0W62suyUQcDGJVjMzSg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvbStBZmFrYkZ2RmhnSEZi
            alM1by9Ba09McUJSbU52aTRtcE1DMVVzYVRFCkxWSUZxSkxhM1VvZWZoaUJhWHpO
            NG5rQ0VTQlV4L3lLZUJPRDFVTWhVVkkKLS0tIFB6Z1E4WXVFSlZNUHplZlRTejNq
            dlhScVd5VFNJV1J2cE5RK1BMb2dYcHcKqcsKmyHfFg2Ibf4ZgPq5DW77G2k3BNHv
            aIdDl2ZEbRDB89ADlcwqWLqaDfprlteCzkjsF7SNw8fHh2mPfg/Wtw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T09:54:56Z"
    mac: ENC[AES256_GCM,data:SdG4uZn69kITz2ejA/kEgMalVBDJj0wY32i0bhKxJ0tlX7eFo0AJ5oBiE3/hAJWPVmWOeFc0G/jRuMQFOke4nCXwiKIVg+KuRd22YZAZc93M9CXo0KKUD9Fjz/hDBvowoCCPRt1DHak6+Td/BA3X8W5qhs7Zzzd5AAOghXR5LNg=,iv:jCsqCP+3+dKwC994eLht+h17ul/8PcjCxo+ySQl1VRk=,tag:0dEzLCdlU+h79VkGQLU4Yw==,type:str]
    version: 3.13.3
