apiVersion: v1
kind: Secret
metadata:
    name: netbox-valkey-config
type: Opaque
stringData:
    valkey.conf: ENC[AES256_GCM,data:IOOW681mHQOJWkBmcc8ekg0oKEoB9suHqzClnTr49FVfnN5PbVbeU16LVE5iyL/El7c7JcTPAXn3Og22UIPYN/Y7Gk0IRe24kzXPxH3muvDHTUAX5fSxuRDFhQeyrCAq32JYwMO5,iv:8ra8fZv1OX8DFgrOfyVz5ngYpyxn2GwWQ5arL8d3wI4=,tag:O5v/TL1gbBstRmkDkkNqoQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtNW0zRitTNXdKbkRYYndT
            RkwxSWNNeVQ2enlhZmlCZW1KT1BMY0xwQUVzClRVZTZOZjRtbk52b0NEdTlXL1J6
            ZkdsOEEvZkdmTi9zMzV5R1ZjWlpoQTAKLS0tIHJpMUxvS2oxMDFLT3U1VlhjSkZ3
            b0hPbldCcFRIYVpkeVg0dElKRHRlSkUKj2h/hzo8NyZ30i6LY+kJRq0AIMQHAYho
            ORH92MtZUMmgzU0mpW4OVMOxdBf/33yi7qEYv17HRS/52yd6+POJaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T09:18:40Z"
    mac: ENC[AES256_GCM,data:W890R/Th3GyYyHf0rMTayZwpXC3A4Febwuz9POjTwHt6GuH9yx18Ve/cTEqRzCRohdjHMnTSHBql2wyM8ozUHhHeBrW+Q9l09L8bW5BQok6ivBzGLdGUUO5Ynk3hfORVFBXnZof4Gd1pF8YpNmOUQ1tjktWJwWBO6FGb9RAbd1E=,iv:2SBAPgwwukjYXMm8iwdLDjuDVJdmczzE6iVRh99exs0=,tag:iS+aaWwufazQ0fGM+LAXAQ==,type:str]
    version: 3.13.3
