apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox-valkey
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: democratic-csi-iscsi
