apiVersion: v1
kind: Secret
metadata:
    name: s3-backup-hetzner-netbox
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:a9N3Jbdw0aojLJeWYCY8rAaY2RFHyjFA/PcgTuApmuifTnmNfOfw73grYwM/8xPTpkIK3J1/DmqM+yk9bnRlQv3J2kxWS16ZRQ==,iv:HcPQeS1NQ51zt7Usn5sPHP6JOHhRAPBh3+VNVr//+K0=,tag:zTyTHvy/DuVhHeeU8Wlu3A==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:knmly8eSVPO+j4AUdF5g5QSsGA8JcVxLolwKrIv0LauOv4J4s/sjdslqe3Jh5/Ev/u1FZgqLIiVpdvx3jHtDwQ==,iv:9B9ZwGL6aKQ5CgWyR8TmMnRx9seJEp9DkU39gzYI9T8=,tag:2BPteFYhqgnJIhDylTRjZQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:MkkYDIIQUJlr/OGtzHeLo3H5gk8=,iv:IzvCogcd5jAe9Bi6hGpIvFJ4haJs3Q57VnSrQnrMDis=,tag:6N2BCjd9Jd4VPJKdhfj4CA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:O7Y/Py+16fZxhe1fwg4+9/rIHRXHdfS6KatOxKTR2Xx1p5/ACCmefw==,iv:DA/mjhsKouZSfhu+/ceStZBZ6JSXYtwhbpfXRf392Yg=,tag:Ojx4W9Gf4gfO4gnfRpKT9A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBScTNzRFBYMm03c0dvZWRn
            NThVU0tGU0w1c3piUTdoWVZyazlZOEpoYW5JCnFKTVBRQVNMeGlMaUlpL2pFdHha
            KzlYNWQ3NDBtSElJTnZKTUtHaHV1dEUKLS0tIEJTZ3lHL0wvVTVIZm1iRU82eGNp
            WW9XdHF3bkh4aGczZ0t5UDV2czk0TEEKcPfzcq2KDm433LOzKfRhuxPWATwk3e1e
            bHQLylzeKpOgQN8vJgiXK7cUrQ44js9x9f0uyAy373QCCvw7oi1xhw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T09:18:40Z"
    mac: ENC[AES256_GCM,data:NxDKi5w+QIO04aNQ3Oo+P0XaJ0CbNeZDwmzR8fofOC2ydcPjXtWnnJ/i9Es3nnr32Sh3/jSn1GA2fuDnTaPeTeoH4y5dvDHG7dqF98hbs1VLUVWh05Q50xGEvEU/x2bc2AkVcYmA1uCNFG3AXnfe0etC40/R63ncYCNwpoNrciQ=,iv:Hr7OngAdkjUkJ/B5iGBOroLL1npBjQkoLh+17SGGMGI=,tag:8fsVmpqKds6I8gK5e/yUog==,type:str]
    version: 3.13.3
