apiVersion: v1
kind: Secret
metadata:
    name: s3-backup-hetzner-netbox-media
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:BuLrgCu1PoEelSzNUgO3cU5ejO/ZSE6ahciAf7ETmcVbLnfFFngOIr5/mAMtXAUBhivmN9QjwV3TAyrsby92jMGjK40xqoMi63kVGw==,iv:UtaQEs82qZmIBDbsNunFEYQ4/mhD7lEtKvgHYHWje2g=,tag:1y2TEFcUYfpsRNVHH6ywfg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:U6mKllJsiNVPOHlSHs4n62wR+FO8fruGtSTtZjLvORhJnw2wcV3d5RLLDaR2wjp9uxs050xkVJaolBdTFpyN0w==,iv:WmgZyzVrqAohUaALHey0WQPwCh3Z+ePZKXrr6VvHvXU=,tag:UTTuNFM1Rcp01NXQolhrkg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:N32cjTyrjvY5JVzwUqeATeWYYhM=,iv:rFmiOBR41KZdfVMigYVCFuAENcenHNbR3iyWRi/lzl8=,tag:N3PgO4KlAWrRXdj2UICWZA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:vd35bDr1kDZyWZ2kg43o3BRDi++jwL2KgMZvsnjKrk8c5s81OrUxdQ==,iv:g8iP8oYHUzPK/RK7TG2rHscSMN4FoLDEiMX63k1S22M=,tag:mL8UVocNH0plmNxAXfk9eA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiMnBUdDVwSW9IMFpFcy84
            VEFPS3NVdlNYN2lpV1g4S2NtTlpBNHlhc0RJCjNTa0o4UWtQdS8rNFJsdmhES28y
            QWw0alhCV0dIY2RwV0ZuRmJndXczTUkKLS0tIFRGRUNRSzRsdG9lT0tzTFZKbmFx
            THhyRkcvSHd0VzdyUmVqcHpybmJiWFkKyDdeIcEuRDAEQDvo4ay32CkjNOY1yIUE
            sjjeOjymV5O30yHcA6oY9m/GyVUnGXtlvG1alplQr5dCgqVZ6iq6FA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T10:04:56Z"
    mac: ENC[AES256_GCM,data:XHPn/7q58W/WRwQkU9gko0fMst8OcYuS8FOoTw7+Ua59/NVg2Fmr2d/uNIk91lCdlVbEkOe8E14ZrZidODnPp36WD6t2BPpewSjWYbEdZZdXQe/Jsvq8A3zuHYh7Yc+R6HKIBucTZET/y6v/t3CeQcoUk3N8tSAwhV5vUFrKbYo=,iv:xZ++CqhzpuK6TxQGQzzov5gG8AZ8WKgl3Vttgfllr0c=,tag:em2SG4MfgZRpTfgzJYV9tQ==,type:str]
    version: 3.13.3
