apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: dnscontrol-secret-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - 01-dnscontrol.sops.yaml
