apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gatus-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: democratic-csi-iscsi
  resources:
    requests:
      storage: 1Gi
