apiVersion: v1
kind: Secret
metadata:
    name: s3-backup-hetzner-gatus
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:Z4yu0ajYuUI54//s5f0OS+khkov2SZD14tnLDVjSGxwPBNt1kVRn34sv0tdGvV52X2p6k+KpAzfPNYQHIeGBaBUVqsM6FuQtfnI=,iv:pEv+wBzmvQBrxQl5fKzkQaB/YzsZQOs9+cPrBykIthk=,tag:l9lFi/2lKCzjQoVIqU6rYg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:OJCj1B82XWhXg3u8BluzB0FZBKWA6dIQFK2P9a07DdHJ2KfRl0g8W0uYNyc=,iv:iLSj9Cv6GFv+g/mjGppjb5ChuV2v3Nu28fj5UMj9KiM=,tag:12vavCC0HxHNQcmzmjPCHQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:/7YDYk2cx7omzCVjpDpK2RbySlQ=,iv:l0QOwxG6UXO5CYkuWXFB4CCSNi9j1fm5NobnX69FYzg=,tag:X5JOmwQL+ceqEJdVW6U71Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:4xTtDxJ3I0nZAJCd1vOLpS2RTCjYzgJRKOwJER/8+t8Dsdy/eIZrwg==,iv:ZjhGs/slbX0IKiY994+bhtjFgHLV1rQ8KM1oqLdc2Wg=,tag:qbWmfQQvX+xHoJgfxHsHyg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUW9ENzhTSTNxOGk2STJh
            TVAvZ2F5Zkcya0x5WHVXd010Q2NTSlM0bXdrCll1WVN1RFlld3BLL3V5YnYwSVZu
            MXZVSzEwQk5jOStqcXIvdkV0elRUWTQKLS0tIG11OFVxelB1RHBuMFdWYWhWQVNM
            N010eU5FUzE4U3BveSt5YW1NY01tR2cKq2ctNXDxtaGuf9hz21Cm2iXy3xfjA0L4
            XOHZGtuZ1ifolZLz0VDw1t5VFqK0rZYyoG55RBkb498PsfIJ0xW+bg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T10:44:29Z"
    mac: ENC[AES256_GCM,data:hIsgWiA2TJjFewlugp7096+tGk+w36tqrnR2vXme+ddw25WRYWqIyEN3UkKsEDoW1BXS66X4P8igTjLA4oA7EKSKDsnVcToxDtfbodrES6juvNrhX3J6ZPFskgKrb2KqXvL9FjlLsTN4jax593gOkV2TsoHPIDXdz5UIDLHmvwY=,iv:TLi50cyIUewCNeM8eohE/RnWZbhXQETL+2sG/zh5J9w=,tag:qwu0PbycRqpqRYtowTfEFw==,type:str]
    version: 3.13.2
