apiVersion: v1
kind: Secret
metadata:
    name: s3-backup-hetzner-gatus
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:Z4yu0ajYuUI54//s5f0OS+khkov2SZD14tnLDVjSGxwPBNt1kVRn34sv0tdGvV52X2p6k+KpAzfPNYQHIeGBaBUVqsM6FuQtfnI=,iv:pEv+wBzmvQBrxQl5fKzkQaB/YzsZQOs9+cPrBykIthk=,tag:l9lFi/2lKCzjQoVIqU6rYg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:OJCj1B82XWhXg3u8BluzB0FZBKWA6dIQFK2P9a07DdHJ2KfRl0g8W0uYNyc=,iv:iLSj9Cv6GFv+g/mjGppjb5ChuV2v3Nu28fj5UMj9KiM=,tag:12vavCC0HxHNQcmzmjPCHQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Qy4GEwApynhLvO+ynsK36lYw8KQ=,iv:ENJyi5EqNDybcBkwSJrE16RyobPmvOeSfaKHZxcsbHs=,tag:Ta/JvYvWmc3YCDn+G31c9Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:qcYcAYaqHgUMOd0Fhqvsv1NJ+uJ35LFBAtFTYFdIhhaNcaY2ZrixDw==,iv:h3VwPpcLd3o50CPeS+eiLOQ8zzc5PxK0XorvMDGvaOM=,tag:PzjtPUwuSvZEYBajRkGoFQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUW9ENzhTSTNxOGk2STJh
            TVAvZ2F5Zkcya0x5WHVXd010Q2NTSlM0bXdrCll1WVN1RFlld3BLL3V5YnYwSVZu
            MXZVSzEwQk5jOStqcXIvdkV0elRUWTQKLS0tIG11OFVxelB1RHBuMFdWYWhWQVNM
            N010eU5FUzE4U3BveSt5YW1NY01tR2cKq2ctNXDxtaGuf9hz21Cm2iXy3xfjA0L4
            XOHZGtuZ1ifolZLz0VDw1t5VFqK0rZYyoG55RBkb498PsfIJ0xW+bg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T10:18:16Z"
    mac: ENC[AES256_GCM,data:NOId85NpcaK8ItfO6OQkI+wUGW/fwaJOOCQT3V9KCdWyRB+I2OyfjRRGdiZA3IzgNQL4W9oSxlaBP5HDg15U4KRHSTPA5ON2CHf0jzRpcQiewYaX/jP2Rvdbnvg+mqEvG/3mt/DTKQh8bgTrRUeYEHY+uXb6tZq3932OCuhKNaY=,iv:SxkAqViFR+Nw5/BomSW0qHmrIXiqU8pzwwBQU4T/UUA=,tag:ctTjTB4VXiLaYSzC+zEycg==,type:str]
    version: 3.13.2
