apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
type: Opaque
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:iWdk5fopyt4pP1/rn0a2F3Q+5AzuPHa0mxCxiN9h7Q4ylrq/e6ONMv/VOKADk1kArE68WgRzm8PF//5XuQ==,iv:DJpqPpldhFRnYy45cowRiwRM3y2AQeISNH+vmooYLx0=,tag:fgFXX/gsgfG19ESJVBDufg==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:D5csND8EtX2uQEpXXccmhOjhM9j7EkI=,iv:ZovZ0TwZfFx7emDcP+pLO6taAEW9GiJataBygMQfdl0=,tag:ZLl1W1XqNmIHg/XqvOsS4Q==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:6O4iqm5lCIO5c7Xkgqo2u0ub98jAjJKcr6Qh7WFJyw==,iv:pfX0nRnbYT0UbYBeZ74MAZsgEoCsaHOhIvOedmiG9H4=,tag:ak6wHyz0ggqvNsOgdItEXQ==,type:str]
    PAPERLESS_REDIS: ENC[AES256_GCM,data:NP231+YjhE20eiwFuraGjEzmSHoa9zMtnwawwfw4D5wLi+Sjj7fwrPb2p50O0noG40ZNbxsHSaBnUpNxWsA=,iv:EjjIqgypWL3Z1Mthqlnp1z4rOLE5YiAIOIBGq6n3fHQ=,tag:pIzmBhc/xtOqdVXNlaLfSw==,type:str]
    PAPERLESS_AI_LLM_API_KEY: ENC[AES256_GCM,data:8GIoS3EldGIwq11ILqEi4PIMneThCGPa7xK+xPJCyNsrcl5b8QuCOBS7oAx0F7ijGczp7IYyquOGosCJK/tL7sGx+Wqd2RDOhKDZnDMwC9vdTlSjH2spI/4ju8MMyPVbRQqjjyyHKFup8iJwIG+u3hLGD9OAlovXZm1/yC4htYE0vh7T0vX4RjBRb/U+Z3SbGTKgMF8jiHFOTrIjsxbpe+niMh4=,iv:g8YG9i6j9UDciwe9CBexIdQ+I0cjAsDGOw4XveHaTE4=,tag:TZ5uhHRgrjio85pX4HZ8ZQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMbFVXMzdkQXBTQm9jUTd0
            elBxbFNGZVFRN3J5WUFVMmRpaEFGVEhGY0NnCkNhYmlvTCtBWklpZlFnUno3amVj
            eDdwTk5zZkpzYUJkMENaSWI4SE1FTG8KLS0tIFVYL0txUWJBYUxPNDA1eVk0MnhY
            SE1DMENLL1lBdmtPNmhEaFFJZjRmVTQKaONgEcgMnsmHHM8G6iBgufpRXpCDb7C/
            Mq5Fbt5nie/jZCf1f7s7nOXX26SWePy7eRWOuEH94vor8WcTrltx4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T09:45:24Z"
    mac: ENC[AES256_GCM,data:skl9D5tYn4qzdlqcfPAevJlvWxfap7cLwodO4zzgdD6/aJ4T2f6ckPI+l1W5fTV/PCPanh4L5lspjgPUXRI0Bt4E6mvks4efAn5tODNzP0fxx2OyURNbao4Sj3SBD7l4UryFV9M+5OgO8hz7YYrl/jjdrjGA4kB+g1aCxjZvnyg=,iv:WHyY2oB6dWBKWcEVh0cPTHAjIhNWd04hfaGk8K4U31g=,tag:WPlcZHBxb2C267VJ/D2oWg==,type:str]
    version: 3.13.3
