apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
type: Opaque
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:iWdk5fopyt4pP1/rn0a2F3Q+5AzuPHa0mxCxiN9h7Q4ylrq/e6ONMv/VOKADk1kArE68WgRzm8PF//5XuQ==,iv:DJpqPpldhFRnYy45cowRiwRM3y2AQeISNH+vmooYLx0=,tag:fgFXX/gsgfG19ESJVBDufg==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:D5csND8EtX2uQEpXXccmhOjhM9j7EkI=,iv:ZovZ0TwZfFx7emDcP+pLO6taAEW9GiJataBygMQfdl0=,tag:ZLl1W1XqNmIHg/XqvOsS4Q==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:6O4iqm5lCIO5c7Xkgqo2u0ub98jAjJKcr6Qh7WFJyw==,iv:pfX0nRnbYT0UbYBeZ74MAZsgEoCsaHOhIvOedmiG9H4=,tag:ak6wHyz0ggqvNsOgdItEXQ==,type:str]
    PAPERLESS_REDIS: ENC[AES256_GCM,data:NP231+YjhE20eiwFuraGjEzmSHoa9zMtnwawwfw4D5wLi+Sjj7fwrPb2p50O0noG40ZNbxsHSaBnUpNxWsA=,iv:EjjIqgypWL3Z1Mthqlnp1z4rOLE5YiAIOIBGq6n3fHQ=,tag:pIzmBhc/xtOqdVXNlaLfSw==,type:str]
    PAPERLESS_AI_LLM_API_KEY: ENC[AES256_GCM,data:ZlwHJaj4o0LRe7h5ExtD2+eMmFO5MjUU5PZU1JAAexY/GMocHEzeEgCHOLunACTVMeZX9ORMwImNEfLDXDYQ3JptdXMi3J/CYW8LmNDvAo9yIVTLE7yjnhhBWj2mHd1f2N7yvbag6MxL4jtKSluOLZkmpw7jdFXgP4sM17QzZ1+h8jkEPX+99XSnsg/rdDAzH8PLGscP8kvJkag+fN91kl19QkA=,iv:DST5+5TMJ79GUaJQZN4iSk/Su2vHs/1O47Rji3uHpyg=,tag:c+ME7/YJdztXSe9Z0UY91w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMbFVXMzdkQXBTQm9jUTd0
            elBxbFNGZVFRN3J5WUFVMmRpaEFGVEhGY0NnCkNhYmlvTCtBWklpZlFnUno3amVj
            eDdwTk5zZkpzYUJkMENaSWI4SE1FTG8KLS0tIFVYL0txUWJBYUxPNDA1eVk0MnhY
            SE1DMENLL1lBdmtPNmhEaFFJZjRmVTQKaONgEcgMnsmHHM8G6iBgufpRXpCDb7C/
            Mq5Fbt5nie/jZCf1f7s7nOXX26SWePy7eRWOuEH94vor8WcTrltx4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T09:37:06Z"
    mac: ENC[AES256_GCM,data:XK2BrdnnmCmn9t3zJq4AaR+bKcGzm9Qrf8FXS1eMMmq8+SReoVIqHQiWvQrC7QF1y14k7oGOcQ5wvsyjaaJ0OXz5KaPZb+qboJWEbYgkHxZ+yJS17wxia5R5AR0oYUtCzUt1V890X1oVjRMug5XjzAXkoCPu1a7nkZwWQ5Vy/iM=,iv:XfuF/GGBhXqOWyk+SDn/VV5Rt1IFQvMqZTtYmEDrSWA=,tag:sVIGlPWNCryXXTjwxAErxg==,type:str]
    version: 3.13.3
