apiVersion: v1
kind: Secret
metadata:
    name: paperless-valkey-config
type: Opaque
stringData:
    valkey.conf: ENC[AES256_GCM,data:WYtvUGFDhf+9zx4P9t1OD5mCFhZYX5oXcvcNiTWqzjwu5cKvpcIXu3udhX779kyZtaVsfauRvifx/6lMRTmfml5zomD1,iv:GcPsKt2EQtGa9GpNO7vpLw1NmhhAaviEpCZnkLRlm+w=,tag:XCKWs6Wbvn1LOZUrVK88jw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlc3BQdSt2ZEhrT2wxR3ZG
            ajl6Ymg0UzIzaUQvU1Rlc253UlJpbGtrQjIwCkI2RXQyb2tuc01HVFI5VXZDOEFK
            cXArT2ZjdVpvTUlscVhlS2tOV290ajAKLS0tIEpURFNkYUNoMUNLYXhpbi9BdDhV
            bXZ6bFh4U1pSdC9WNjQrcTJzVitLZlkK8jLaGRekPasudgwIu2vd/+fiFe3GwIu7
            Y24+o1o5SAaNMZwJC4SFu+pIWH1nvdbbu6k52CW4Md2nAAyGChnr4Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T07:13:21Z"
    mac: ENC[AES256_GCM,data:9S5i77U2mQDdp7uKldSPU6zaSp0fX8f6MKSQHVuFyH720G3cg5iXagUGhgH1rWKMM439Tv/BQy818QmrefploDLavflvGxl+Q4A16xW8hjIRHzX52KXr3d5J5tWkEJX9m+xuwNndDYx0MI+TAN9UMwpKbu2J9SyaXL2yhWEVBOI=,iv:kdzZhY3IstPBn9uovn+0fyhtH5qCHF9uheFHaOVmDhE=,tag:zrpHaQPtYeLs4f1p/tQpsQ==,type:str]
    version: 3.13.3
