apiVersion: v1
kind: Secret
metadata:
    name: s3-backup-hetzner-paperless
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:VWvGVVO5CIEN6wjlUOqaypbw05vD/GzKQiNSBUN4DONRR+0RGZgxMmG8nlaSGGMXZdsGIRgLeF0OKU3Gc2Y055N15R99pmVS0w==,iv:8lzmk1+DjiLq5lOLk64rgMNb32kn0irip5AwiRkC1QQ=,tag:yWdACY8DAANa6Dm/gwyX2g==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:s7Uk9LbC9giRyAt9eLtHYOPqWM2lnlhyEBtQ+gyWDg==,iv:FHKXal0fs1AbGb1bn6IBrBT4LoujerR4znEHdSyFlxQ=,tag:a882VlP+GM3Vi1XdUoFG8A==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:6H28XfXUsy6dhy2c+TdygOWHWk4=,iv:2oxyz/N4zJDJl2sgcHqMifv70zZs3Z4tdoXBzl0XbVA=,tag:/C68YmNGlnV+rMrLfiH+jQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Ek/X18cNM1ZGDzvshN2PmUuObUnwJBJFm7vEHeBCcc8wDUHDHIZ8og==,iv:KYEn6m+GSjBknIaUaJIO7jeRlO13ZPo+oxyLlyQw5Os=,tag:YIrlb7iMddpTXd7WF0Przg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRm8zZVZkemVyRC9oeUlj
            NFlqZHZRRXMwU3owQVFyZE5yd21UZDh0QkJ3Cm1Zd1d2Z1UvVjNicVp5a0x2anlN
            c2ZtZ3c2cmZMb2xyZXlsWTdSRm5ZWTAKLS0tIFdxQ0ZMc3pKdjhFL2tvcGo2N1pS
            VXhLOEdLQmRkR1ZXSjRCb1dzeWwrSk0KFz1OS9k1FWTImRMnPstaxoOteN3EjhXs
            XZ7AlNLUntnFkwqEcVuWBWG/A8It6TNVymBZZhc6Y2T9RezHJgBqoA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T07:13:21Z"
    mac: ENC[AES256_GCM,data:imh1D63VajTyPTz67nhU+D4nLiVbT/UJgr3P6c+2NLg/CeCEOQClHtSWw/lstFZ47Mp+kwBaFKxPRIwOhgl4csbP6n/JEf3XldIrTSoMuLk90liczLXcVbESQjmzqCm5HqBCgy20P3ky1SX73Gt2wnxD/yuC72Ve6siKDyY/0YI=,iv:AB3r8Khva7kwrBOxYqSocEnc9beaGcbgGKx9dvFhJUk=,tag:YLlC2DIXIHDRpt2kN+KQnw==,type:str]
    version: 3.13.3
