apiVersion: v1
kind: Secret
metadata:
    name: s3-backup-hetzner-paperless-media
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:QvWfkD/6BmKW1N2AKk8SjfXewAoNNCU9rdhgEjl7bBUQlQDdgCeba52frVkzU/U67wKJNpP8NGPcQC/6GDbkxQlH0x9H8wHTF4Horutoeg==,iv:xECE+wWMJlw8KnXrGA2RFziEO/ZZJSvnAXxnRE2DIPU=,tag:QoaRiQ98I3fJUdgfYSIKQQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:TsELqQyUwurn0aTTdebfLTNvBEC/BID2Ny7Y8sEO,iv:HwBnURh5kUZOplDnGEQ7lZH4CG2OwsdZy9yz/GYmlJE=,tag:KgSZkCxpQs7pT4hFIVQVFQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:EQ37jvIF2FXDmLmgXuiL0hbVr2M=,iv:Q4KVfXRBSMNmIw9tMGy8ItCQWMdZTQwPHrEMqjB7qsM=,tag:+IZd4CeQYapPksa9CzlI3Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:CyPk3aefdLsTsY54JJAFwulpNgm8B1WAxc7OcMr02H5VZxNycxZFBA==,iv:gkClV38XQxR5vH2lxSUO+za42XcWDD+vEouYGaKmyt4=,tag:dHcdqsZL5w6ObCfUZqJA6w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMjl6YllIYklJTzhzaWRq
            THJESzIvMmQ4cVUyODZTVEN6VElhY01ueERzClRMNjZWZmwwVFF3QklteUlHSWZJ
            cWhlV3pONkFTTzFkUlVNMktYdTBVZWsKLS0tIE1BYnhrK2dKY3ljV2FMWmxDMUw1
            ZlFVRVRGR3VpZmlNZm1ueHlUbGJ0S3cKpaT4eA6nlfAiAb+GJnLPGQNHytFVSlaD
            jgqiDhfADXmhGtCwqgXvUq3o4erys2Vzk2uikIpyKibKOYzRyfZcxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T07:13:21Z"
    mac: ENC[AES256_GCM,data:8iIijdQ8wUS6PC1eE4d4+RZq9/LfI2OZymGp8VdmwP1pl7kHZemJQ16L8JWZatTxlqpRXKdUF0T6tueAarMWoLvhlSmgOf75+hnJxnaRgEVBJgyzT9kP+hmYh2O3RuUu+PqO+YyX4JYm1rI5F9aoBfWTVkgi11/MJ2kV8a8VLqg=,iv:PkB13LqZn2Kz84fY4qGejMKviOv4RRi+BA77ovbGiLc=,tag:fWQ9hAhijtb69TxWoD/W0w==,type:str]
    version: 3.13.3
