apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: paperless-media-volsync-secret-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - 63-media-volsync-secret.sops.yaml
