apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
  name: tautulli-config
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  mountOptions:
    - nfsvers=4.1
  nfs:
    path: /files/kubernetes_csi/tautulli-config
    server: 10.50.1.200

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: tautulli
  name: tautulli-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  volumeName: tautulli-config
  storageClassName: nfs-csi