apiVersion: v1
kind: Secret
metadata:
    name: s3-backup-hetzner-tautulli
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:FNtCbIZJeqoFhps9ZjwLOv1kRo4OEhI6GgnWjUnljF/19i+OAhDJpW51W9ecp9cR4LAQ4XbhImeWHu2dUyFxgT4x5nY5hhAJqxSVrN0G+g==,iv:lRfRtQEaqK/FQf1XLzu0EjSiux1IhKkRf+4Q11PDhNg=,tag:T0hB/xI23QyA6j+hkFQOJg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:i+nl9IKDYPVozaJsYyqL8ZbNwISZzgincM93LAILoguyxT1//FcCZIBvjes=,iv:At/y8g5BQZPUXWKdEfRBWjsSQ3AHEg3G2Z3dU16GczE=,tag:9aUndQOsTc0C6rt1FU9LYg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:hnBR6QYtpkzM6/JCH/RB/OwEUVU=,iv:qsz6ASrH750BGpkNI0SAZcF6F6wdFqKWlUPYUQvV57g=,tag:hY8Y0pRbmpKMcUXjhSkFDA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:lxNEoXEs7iYfOfDa+Y03i28yMd11D/m8qKZXU6njXtaQUlMMhk+G5Q==,iv:JdyiaxZwhNA9xdos/sDVL98KurQkR/nBsD/KiCpLO78=,tag:zEPVEcNn91nwuIrmqs8CmA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVWxvcWZoeFRKTUtwcysr
            L0VMNEZCci9nZTgvdTM3dXJDRkprdndaMEVJCm8ybjhJdmdjbFdKRjZHb25xM0RL
            bWlxeXBtbHdJZ0xVYjA2KzVrUXNJSWMKLS0tIGNGVEwwTkFDMW4zYXd2cm15bmVo
            UjVEQW51d2JxakxXelNqUHJDUnhINDQKmhO102WtWIxesLSnJ+UUcBaxKq0GHSdQ
            Gw/FOhKhgYddmJ/pJQQRBV0XMNegNzneoFUN8PNG1uV2hm5DxbjYrQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T10:44:28Z"
    mac: ENC[AES256_GCM,data:M0l5qIicPKlxzhL9gPxPKJAjlRLg2qQPvJAvceeSEFh4SEULuQsZSpu6Y1Wbd2iMCbFTnc4VKvKaR3Izsd2O0t73qr5SpYiAOqKCD1Rq/JvBlvnTqctX2UnH05cXfYcPEVQXklk8JaEId8/HRb/ERRzfPM/Bk7Uq8BnUp1MwZRY=,iv:7mxVtZfozQHzJeUulLM2KqOsCdfAwI2x73usT0+a6Mg=,tag:Bc0hh8rjWI65zkaaojRSnA==,type:str]
    version: 3.13.2
