apiVersion: v1
kind: Secret
metadata:
    name: s3-backup-hetzner-tautulli
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:FNtCbIZJeqoFhps9ZjwLOv1kRo4OEhI6GgnWjUnljF/19i+OAhDJpW51W9ecp9cR4LAQ4XbhImeWHu2dUyFxgT4x5nY5hhAJqxSVrN0G+g==,iv:lRfRtQEaqK/FQf1XLzu0EjSiux1IhKkRf+4Q11PDhNg=,tag:T0hB/xI23QyA6j+hkFQOJg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:i+nl9IKDYPVozaJsYyqL8ZbNwISZzgincM93LAILoguyxT1//FcCZIBvjes=,iv:At/y8g5BQZPUXWKdEfRBWjsSQ3AHEg3G2Z3dU16GczE=,tag:9aUndQOsTc0C6rt1FU9LYg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:KhqXk8WYVXn5Jdnxh04ffD/ULBg=,iv:4mpszy1CjLWxdgJ6Xs2knUOtgp6NCab9lCrG4bikKbw=,tag:4iD7rUDMbEh1txvzO/lL6A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:3KS/0xYDiOUvECEvtCwKPnSUnY9jv88zs2Cn/Q5uzliKYPGvR9Ks/Q==,iv:/oRaOSoWLHOQBM3ku69sYLfAc4TXTe7n4/SUnQW9LhA=,tag:4V60+dr6/PwiyQ3U133G5Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVWxvcWZoeFRKTUtwcysr
            L0VMNEZCci9nZTgvdTM3dXJDRkprdndaMEVJCm8ybjhJdmdjbFdKRjZHb25xM0RL
            bWlxeXBtbHdJZ0xVYjA2KzVrUXNJSWMKLS0tIGNGVEwwTkFDMW4zYXd2cm15bmVo
            UjVEQW51d2JxakxXelNqUHJDUnhINDQKmhO102WtWIxesLSnJ+UUcBaxKq0GHSdQ
            Gw/FOhKhgYddmJ/pJQQRBV0XMNegNzneoFUN8PNG1uV2hm5DxbjYrQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T09:57:11Z"
    mac: ENC[AES256_GCM,data:SrUWPPQk/JSgAwlipT9Jk75B8IsUiri3Z19zvUNReEiEc9lzhj3+HKq1G5xE1n3OlYM0dBJaBAM2TUii9wDapNLUT7r8U/n9AqGXQns05tAa+PzukXjWC6dU1Qc/RnQsQuNaDVnaJE2B0bddciLwCcyTbEb8wevu4lCUK9SIjMk=,iv:0po7IAR4skGtu6fKJu1RlhF3VX/TCI+w9ndK/tU0O30=,tag:BK9rEQ7a/QlaYWK6eKtYlQ==,type:str]
    version: 3.13.2
