---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: bgp-peering-policy-worker
spec:
#  nodeSelector: # Delete this line to apply this policy to all cluster members
#    matchLabels: # Delete this line to apply this policy to all cluster members
#      io.cilium/bgp: worker # Delete this line to apply this policy to all cluster members
  virtualRouters:
    - localASN: 64513 # Use your cluster's ASN here!
      serviceSelector: # Delete this line to allow all LoadBalancers
        matchExpressions: # Delete this line to allow all LoadBalancers
          - {key: "io.cilium/bgp-announce", operator: NotIn, values: ['fakevalue']} # This will allow all `LoadBalancers`
      exportPodCIDR: false
      neighbors:
        - peerAddress: '10.50.1.1/32'
          peerASN: 64512
          eBGPMultihopTTL: 10
          connectRetryTimeSeconds: 120
          holdTimeSeconds: 90
          keepAliveTimeSeconds: 30
          gracefulRestart:
            enabled: true
            restartTimeSeconds: 120
