apiVersion: v1
kind: Secret
metadata:
    name: tracearr-secret
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:2o07QTg8sEviS+JYWZf7UKXkczfhRs2ZZJjgpPYGgtde1J2pcgape5XPzSYHM8kDKKdXrbaB7bo1KrNRw8nhOA==,iv:lGiwMnzppUA6ql8HEAtUv5IAL2uvFhoUELg+ZkqLMEE=,tag:oBdo20FKnW5eEj3v4wJGHA==,type:str]
    COOKIE_SECRET: ENC[AES256_GCM,data:P+b5CxUmjO8Z0Ru/TQzz5f66mYhwYdzDVMExxhikrfIxhcWvUWvbXzCPgC/yoQqbYQ4Ige87K3NPBVTlhq0LDw==,iv:iBSOyNXl8AP+PQAIP11TQlyx9/0iLeiRichSJRFi9XA=,tag:9E2/riKkUXRXblFPDpyh/A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6V0pHUDRMSVJ0c0puVVhE
            YkVwUkk5T3l3OHo2VWRFSnZjNDRBZXBQRmhvCitwZ0VyV2xGRW1jajZKK2lBQVBv
            VVVxYTNmWmJ3anVldS9mcVBiK0hwVkkKLS0tIDluenFtdXRkRFVhU01WV082dWk2
            OFcyaVNwUnMzc1dUTmF0cWt1Y1IwUDAKKnxBpCCNm7yj4qCnx848AX3a1pySfQg7
            H6C0As075EtOump8cTpHKcUYIxnYHvgFRlSHgi5UZIL9QvA7ejwY9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T17:43:31Z"
    mac: ENC[AES256_GCM,data:Ea8Kj/f85oCnMQjzOK8STCTFvei1B7DlhCjsphI7+FEbAudnsjmC6EiAb0gTsy2kwhDE2YzGnWqBFd3hVYAwiqR7JJZOhKG//C44aIfdqxwbZOZInHKpAEwwy/JL9rhi8HVRqnzKzDVxJ5vboHqWjG62+l8r13kRCyRMYYw5s8Q=,iv:Qy6P2pgldWQZRdYF7EXvnDwpZeYlyAm1pKKpTcAet5A=,tag:gvrkL/EmMULLpmiRrhAk8g==,type:str]
    version: 3.13.1
