apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: timescaledb
spec:
  serviceName: "timescaledb"
  replicas: 1
  selector:
    matchLabels:
      app: timescaledb
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      automountServiceAccountToken: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - blix
      securityContext:
        fsGroup: 999
        runAsUser: 999
        runAsGroup: 999
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: timescaledb
          image: timescale/timescaledb:2.27.1-pg17
          args:
            - postgres
            - -c
            - max_locks_per_transaction=512
            - -c
            - shared_buffers=512MB
            - -c
            - work_mem=8MB
            - -c
            - effective_cache_size=2500MB
            - -c
            - random_page_cost=1.1
            - -c
            - wal_buffers=16MB
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: tracearr
            - name: POSTGRES_USER
              value: tracearr
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tracearr-db-secret
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: 100m
              memory: 768Mi
            limits:
              memory: 3Gi
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "tracearr", "-d", "tracearr"]
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: timescaledb-data
              mountPath: /var/lib/postgresql/data
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: initdb
          configMap:
            name: timescaledb-initdb
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: timescaledb-data
      spec:
        storageClassName: democratic-csi-iscsi
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
