apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: tracearr-db-secret-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - 13-timescaledb-secret.sops.yaml
