apiVersion: v1
kind: Secret
metadata:
    name: tracearr-db-secret
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:qt8k61NbH4LHbgIbzwXfDGAL2a0Xs/ysIBFHkXlICum6hLmGKw+PKIWXrp3Ic3WDC52SGmLvtuu7La7phPoGew==,iv:q/bijz4RXcu0XBPwsSO7PnajyQ2mA+ljQ3wJRwnX2B4=,tag:OJ8LmjGcgX83QDD/bVrRdg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2OURkNDFrTFMyMlBPWW1h
            Sy9JNWlVc3pwOVFQdm9lMVNxbXI1Wi9xTXlBClh4bkN3d0w0YXBoV1dhU28zRjdL
            TWFwZ3BDTUtWVVFldnFlanRUbjdFOE0KLS0tIEtJSmViRzVreitGQmRkU09scHBM
            U3VqZUpidSt5MmNjb2NCaGZnRUE1WmsKC+YJIsDcOnerj6FIs+cl1Bk/6Lg9TlhD
            fIqvRo8U0v4A278XevCsJspeL3ND0c43L+JsRl6f29Fqvh3NptckGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T18:07:43Z"
    mac: ENC[AES256_GCM,data:MNWAeeSU8ksXj2P00B96Ur3hECHozwg8mJsZYAIdGsQ35YzsQqTfJ/ZxijtIKnJMiuyJzo+S5cHybzhWJp8lZlw+r/b8qVDfCfMXIenBlwydUn4QxDjL+z1F+xBwr64IUWW7k1/cVZIaJxhsECafDjLoyAmPqPbEurbDo7XChiE=,iv:nm0ubXta/ghehR2CyMQm938Gm0Uc/VEt4HSmJR7yzoE=,tag:mZFT98zIeHPwNHxqEMt6YA==,type:str]
    version: 3.13.1
