apiVersion: v1
kind: Secret
metadata:
    name: s3-backup-hetzner-tracearr
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:O/pyxx29Du87sSXpw28Hed3gHcquT/4R83tSS53gvcCyt7a/JgFa5sWlJOWlNPFyno3e2NEaHJCWRHAJ+cWxr7yLB+K5Yk2aVEWbNqw=,iv:zaVIYtCUKDJYqL1jcG517rnqxBOAcs2+j0zcfPZcjec=,tag:7HUrgdcvEiMN8A19XPfxOA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:r0c8QO7l8YiTtLkIx2CFfe5mjP3/hrovYrigqjjaOiqqHqgTsecUC88BSLQ=,iv:qXfy6srvyQN3OvzVde3XHqwA30IQAdn2/RWpgnX9FSs=,tag:/Y+jPVaMSTQshfHnfSjTYQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:uFZwF2O6hxgWnJW5YAQCeLPGhdg=,iv:bPPCVc3wqpnUnTz/BgQ/VoV1VuoQKrrmJNkzS3x3x7Y=,tag:NkZHEM3DQn4HJEPH/uZc8w==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:im1BmoCv/wkpqlODVAEHU7pIhoV3gLFVp41P690XpcPPw5UYPBSAEg==,iv:uC3cNYX8RwTOnaCNdjinA8cjlyD26WH0s44sjwA1QbM=,tag:ckYMAwiR+15KPlTDhcBjTg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UUErRHh1dHlxZC9jVXdu
            cVhqTzJZYktBUWdYWS9NdE4vTXEyREJQd0RVCjdjMzBCeEw3cDM4Q2g0c1lJWVNJ
            UTYzcGJERW5mOUxnVU03aFNQcjBaUDgKLS0tIHNRWDNSM21ZbytVRDdVNGVGRnJx
            OEo0S2k5VmpqKy9XZUd4SFVRVUoyU3MKLC3OiWV61qmM0zE0Dd59O63wH8SlFJE/
            xKDqo/5GlXxzCNe7+KWWCg7swH10rP5IG2yKorClLDv+k7cekLsuOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T10:44:29Z"
    mac: ENC[AES256_GCM,data:I2uPyT2bDTdlqSy/eTqubcc9k+H0pMVcVVKof2LB9Ke64UFgrb2mia9gBMQN0D8Q5H3BOOIjveu2nIZ6IY1xYhhecAsT6msPFL0bfHHr8OLbVDsOu5Kpx9hD1u/i7kzP1fgULPZwaMhsW8XZ7IoU5rWtNku8k17VmK9diGmnQs0=,iv:piwA2W2hOsbJ73PshnBNIWM0pZwYleqILzQU0ZQEnbs=,tag:B77aZDjfhOy/er+g/ywfww==,type:str]
    version: 3.13.2
