apiVersion: v1
kind: Secret
metadata:
    name: s3-backup-hetzner-tracearr
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:O/pyxx29Du87sSXpw28Hed3gHcquT/4R83tSS53gvcCyt7a/JgFa5sWlJOWlNPFyno3e2NEaHJCWRHAJ+cWxr7yLB+K5Yk2aVEWbNqw=,iv:zaVIYtCUKDJYqL1jcG517rnqxBOAcs2+j0zcfPZcjec=,tag:7HUrgdcvEiMN8A19XPfxOA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:r0c8QO7l8YiTtLkIx2CFfe5mjP3/hrovYrigqjjaOiqqHqgTsecUC88BSLQ=,iv:qXfy6srvyQN3OvzVde3XHqwA30IQAdn2/RWpgnX9FSs=,tag:/Y+jPVaMSTQshfHnfSjTYQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:YruigBG47R7r4yHwZNfV6iLafFc=,iv:GpvKx+NrEzSPaPNzJzxPN3YIPrsWmei/PAhyWZad4+o=,tag:LyqeJYV0q34mtXarClPmtw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ZmKw2s250QX0ZSHL73OgVKoingGS4AeBTntqnceOadVxskSp7VcvDQ==,iv:/P/20M/U13Jckk7lkLMCckcmNlDhxmSPOz0gFFo7rbY=,tag:s0JuBNP6vlhgaT12PVgJeQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UUErRHh1dHlxZC9jVXdu
            cVhqTzJZYktBUWdYWS9NdE4vTXEyREJQd0RVCjdjMzBCeEw3cDM4Q2g0c1lJWVNJ
            UTYzcGJERW5mOUxnVU03aFNQcjBaUDgKLS0tIHNRWDNSM21ZbytVRDdVNGVGRnJx
            OEo0S2k5VmpqKy9XZUd4SFVRVUoyU3MKLC3OiWV61qmM0zE0Dd59O63wH8SlFJE/
            xKDqo/5GlXxzCNe7+KWWCg7swH10rP5IG2yKorClLDv+k7cekLsuOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T09:57:11Z"
    mac: ENC[AES256_GCM,data:y5didE3EV8z4ciBMCyUt62NdXVdaWnjZdaS8KPXSgKpNDp1XgLRTmkBpMECnRTTeVVIzR7XHfnOR56rwSBs4Vwg/jvB4PDKj9RCiUP31tu6sDy1Bg8hZAu5sEIbEZ+OZInMJZRSsArsZr/X6MouOgfVmQ+gQxAOQT4kaXa1XwPg=,iv:hsY1YAQJEsRFO6rvrr7/AtKpYYPd0uOD3o0MttdMRs8=,tag:YvnvNXdleMlGbU/TJ2mL7Q==,type:str]
    version: 3.13.2
