apiVersion: v1
kind: Secret
metadata:
    name: librenms-secret
type: Opaque
stringData:
    #ENC[AES256_GCM,data:3KrmrTD6J1nUWYN0vEamMQkmC7GxK0G6ZHbOcnaEzFb9XyqNnGO2jdKTuvg47nOLElv2J5s0oko3n45noDV9wtM=,iv:80EOdTDBiAycpU09kDlVrcs7Nvk4xGlBTYOKrxbtmfM=,tag:pkZ8GrJKOlmSh1+4CGqQdQ==,type:comment]
    DB_PASSWORD: ENC[AES256_GCM,data:NnjCHnAGlJdGavdlVQA=,iv:DG8yhM6GDEqnhb3JAglfIWEnGhWF6MMsvYMMm31h5/M=,tag:pE0SXOptKGTDNqDmFvPhpw==,type:str]
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:3EA/6/95pZbNNk6T,iv:DHunGy1j3xyG719E8UQQ1qYln1Cf3YFiNizeZ6JgGVg=,tag:F6Yj5V0gYQ1JTpR3zbTgsQ==,type:str]
sops:
    age:
        - recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQWdXR2VDVTFNdll4dmVx
            SGRnb2VXN0Z1TXZmVG0zNnVONlUvakhYSkNBCmJBTDRwKzFSdFhSd1NZaW9RNC8r
            Q3FrMTVMc29JNFZhS0QwNlBhb1FRcVkKLS0tIDd3T29HRFJUMzRKWEJZK3liTkw4
            bDRtQ3BUdXNTckg0RFplRkVoeXJibU0K5CkOUI5vrXnm4Wo5EP3bIXMcZJSnPYX4
            B+mvvCMNBOa+V53MeIDJC3sVICewMSSLaMgP7Ef2tPIlEfO91BYDRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T13:02:36Z"
    mac: ENC[AES256_GCM,data:Lguf3TJtbBLeL1wFxxQt7t9Z4aEqbWxTO5Gg1a3TUWvP7IO5TcDoAjCG6oCd1YD2VKoJM9nOxnfzJsMuGgkQTmKZ1rHCShnXySQteEgpPwMAhrpMGCiuN43GY9RYh8nUV9lGtg+8dVM22pO0MHz1LKepuWqK7b+T8B+vs2VjGfI=,iv:Q0eGWPTvx90GQdIZ9mTzH/yn2JPE/g+PXQPTuN+EtHY=,tag:bUsfNmObmsyjnLaGj4YOPw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
