apiVersion: v1
kind: Secret
metadata:
    name: s3-backup-hetzner-librenms
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:p09A0APC8PpIAQujVnbcGbLcnx5nZ7ePEUBOMZP9JTP/QspAcXp1rMx7lekMMccAW3Qo4NAjcPmltBQ9MFbgX5pERbmqFfbSRhpQN6Y=,iv:+j+KEjk9YiFut0lS6Pe0KdQMP5kcj+tdsGsV/NKlfjA=,tag:x79owG/BLMAdAhtC793woQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:k3ciZNwQjIWToBfYTvkg0U3+Sb+fWAcle3Y1s9EVhYajX25oSCpf7NxU2b8=,iv:VW2BghMDLPQzQqQVMcGRA4gPwn8oflHHeqEZ7BsEWAA=,tag:VOJTP4Rk04ISQ/9D1ScSbw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ePBtng6fbCK0ZoqkN0b++E9/4xc=,iv:IlmA6R/JR/PlZ6xF0MebMNebCqVJBxkEbjd1jP+OYDw=,tag:Z0vEaz3jHzRoMZDtB5W4VQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:vzmzB5d7l7JM075ETz3D+2I2182Xzv4XrXTVlPSaLLXarTGxni8Bvg==,iv:0ZlQrnFewiAksczaNhf878sAjelytLVoXL4VUnAiAhQ=,tag:rOX2ZVkFDvsMAhtt27fQPQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBma3dCN1djNWNqNk1GSzU3
            YTRHMlBjQUFqK0tGZTF2azNJWmk3UEFsTjFRCkIyaWxnZGs2bXBSV1V4SW1zN2Ew
            NElrUGhNVU12VGEzeSswTUtROENKZkEKLS0tIFRjT1BzeU5za2wxMkYvWVQ4bXdm
            YXhhaUtzUDkwcThXWU5aZC81OElOYzQKLPSvIm6n2FrsHtSen3dbVXlEVIPM900L
            f/eM5nJFzA8mVEwMNw7wQsMywQaWEKbU0dX62uuxSNolLZty5Bl2oQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T10:44:29Z"
    mac: ENC[AES256_GCM,data:54+5ccGddoXPKxKrKdoGVgMoyei86gi+h6QB5GY2mm4oQY/ab6mMLqotYHIPopEuj51WlldbPt1mVEgbs72qwOM5bcDQ/RCXaT4Hr46cI4Tzpp3IWZTzAKw63Mgf+tlNWi5hVF6x5p7sSVAFxybvvIDHdrSbdA5ObV31v9Hoaxs=,iv:YRMoiq8nMTVpLgvFcGWFlQnb5eYOlk+Sau/ZDpjRzW4=,tag:0uX+/HlrEVW7blG1QtIhoA==,type:str]
    version: 3.13.2
