apiVersion: v1
kind: Secret
metadata:
    name: s3-backup-hetzner-librenms
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:p09A0APC8PpIAQujVnbcGbLcnx5nZ7ePEUBOMZP9JTP/QspAcXp1rMx7lekMMccAW3Qo4NAjcPmltBQ9MFbgX5pERbmqFfbSRhpQN6Y=,iv:+j+KEjk9YiFut0lS6Pe0KdQMP5kcj+tdsGsV/NKlfjA=,tag:x79owG/BLMAdAhtC793woQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:k3ciZNwQjIWToBfYTvkg0U3+Sb+fWAcle3Y1s9EVhYajX25oSCpf7NxU2b8=,iv:VW2BghMDLPQzQqQVMcGRA4gPwn8oflHHeqEZ7BsEWAA=,tag:VOJTP4Rk04ISQ/9D1ScSbw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:k5VgVydAmLMLaczq+t3D/QMOwSM=,iv:9dRYAcI7q1JdbazutWQ5d29DWrmqW8v0TvBYpjCUBvM=,tag:dk+gMtnbI9XenWzNWT1rnQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:x42lSCIU9jbJLOXpik9R0xCMF00+GcycbwtHrrv9/elrvOaK6rFbHA==,iv:v6801xT6HTTe586oXjP1N8IuGN5g2OygKu8jeSOnd1Y=,tag:RwWheflnQvylU1wFG27T+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBma3dCN1djNWNqNk1GSzU3
            YTRHMlBjQUFqK0tGZTF2azNJWmk3UEFsTjFRCkIyaWxnZGs2bXBSV1V4SW1zN2Ew
            NElrUGhNVU12VGEzeSswTUtROENKZkEKLS0tIFRjT1BzeU5za2wxMkYvWVQ4bXdm
            YXhhaUtzUDkwcThXWU5aZC81OElOYzQKLPSvIm6n2FrsHtSen3dbVXlEVIPM900L
            f/eM5nJFzA8mVEwMNw7wQsMywQaWEKbU0dX62uuxSNolLZty5Bl2oQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T10:18:16Z"
    mac: ENC[AES256_GCM,data:QPCjxwCPND4rkRepCYloQoMg4xfCJyRRJzZHOiCjmB80KriXYwwFMS73jPIHpi/SY9dDyVro7gjd2cq6xUddp587WT+x/Lk/fDsj6MtSsm06+CaJ9RkA2OC1KwOFDAKUTMwvK5bhP4KyYSqMOODaDr6CAon0hvE3tbwMvCpyoeA=,iv:PLROeOZcHGcF2D6pvciNyaXIsFXglAQNHg0ZZzA/RRM=,tag:6+hlWYxc/qI0mULUI7kAsQ==,type:str]
    version: 3.13.2
