apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: geopulse-keys-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - 01-keys-secret.sops.yaml
