apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-vcluster
  namespace: argocd
spec:
  project: default
  source:
    chart: vcluster
    repoURL: https://charts.loft.sh
    targetRevision: 0.33.1
    helm:
      releaseName: my-vcluster
      values: |
        controlPlane:
          statefulSet:
            image:
              repository: "loft-sh/vcluster-oss"
        sync:
          toHost:
            ingresses:
              enabled: true
          fromHost:
            nodes:
              enabled: true
            storageClasses:
              enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: vcluster-cyberhawk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
