apiVersion: v1
kind: Secret
metadata:
    name: s3-backup-hetzner-radarr
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:HZZyXHnAeG0bLqmj68tyI7YUpz0gaGFz5GozdYmzEp4gVK+uoDmNT/FiZIzzC0Xq/us15nrW5b9IereBdTPaazxahTVbXajELQuAu6E=,iv:6E5Engw3e4xHnldi5M1a3PzdM8TuTkKKcoGBvD+ONyg=,tag:rDNDb9UIo6PUmJ9QQtKrkQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:HEywEuBHK0flBuxe+HoYCR3JCB/fEXItwsQO/FnA+sFGyJqNAJPUDCvxM8c=,iv:a33xVXJYtV3uwDqVascEkJ60H8yajBHBBJJGv28vPN0=,tag:ZoSut06mrBLkltghHk+7Dg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:055pBEinQ8IGMZRB8+Pyp6dP4FI=,iv:QKAOIkedDxUEnE8T1L1gsGlT2p57AutP5PTjQLA6XYk=,tag:XudOcmFxk7R0nbUJLJlQSA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:2ZW1EFwimiQIKadNon/7HAcPJaD4zLNuEYjC+JTMYMzluFLtR9zgaQ==,iv:Iqs8UZtyu3enOOG7t9LXvMW0hMwrPUDg9CAR/WNw92g=,tag:zvDFpAMtlvl6qUv2HQhToQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWMk5vK1M5UHBicXFRWkxH
            YUlSeW1nODBNaTVtSXVpQnN2L2JwZHY0WGpvCk1nbHpJQzVSUWVycU5QNVQyZTBu
            RmprU2xUMVR0WGlibzVRRXk2NmN3bm8KLS0tIGdaK0FIVXVsMCtlNENBejdsSXY5
            NUJ6WGEzQVFPS3VLK2FicG50dEpyeXMKo1T35AmE/zHAyJFZvbYM0N5uaep1WjPJ
            9MlA+nIO7qrAe8Ks4ePSAooFFZN29t0RnrkifT+A1QiSX79u2kvSKw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-19T17:23:56Z"
    mac: ENC[AES256_GCM,data:u5lK7G77nZKdHjTA/syLj3NOgxlGqWx2AdTKXfH9ak+BBSS1QMrGKQ6V7XNBno4CUgDh6j7+aWzdMODh4khohDncES7obxRCRyBQePaf7xWFhlMFg/32DK7UyzP20ENjDz9HnY0RQkbiouyC0/pK1Mnn3I86EbBjXVfHseI8eQ4=,iv:m+TlPyNf2SwH9JqSoImAtDX+RxJfmlyffDWRYQlku9w=,tag:4gmk8uParFAbsW865hVRuQ==,type:str]
    version: 3.13.2
