apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-web
  namespace: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-web
  template:
    metadata:
      labels:
        app: portfolio-web
    spec:
      automountServiceAccountToken: false
      containers:
        - name: web
          image: jochristian/portfolio:web-latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet: { path: /, port: 8080 }
            initialDelaySeconds: 3
            periodSeconds: 15
          readinessProbe:
            httpGet: { path: /, port: 8080 }
            initialDelaySeconds: 2
            periodSeconds: 10
          resources:
            requests: { cpu: 10m, memory: 32Mi }
            limits: { cpu: 100m, memory: 64Mi }
          securityContext:
            runAsNonRoot: true
            runAsUser: 101
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
      imagePullSecrets:
        - name: dockerhub-pull
