# ENCRYPT WITH: sops --encrypt --in-place 12-secret.sops.yaml
# sops will use the .sops.yaml config in the repo root if present, or specify --gcp-kms
apiVersion: v1
kind: Secret
metadata:
    name: portfolio-db-credentials
    namespace: portfolio
stringData:
    uri: ENC[AES256_GCM,data:vcYJ1pmxcRF6HYLYNouRkJ65MIbPneMnvIX+R92MzEJvLngNAHoLRb9pA3xC4tz0TKU6iCoQLE5Ukcd52Ez/,iv:cinKaj38LyjGv6Td9fd8V3SrcFn7WrLIz/1AygqUZl8=,tag:1Jo18q/7ktnpkp76EcUzLw==,type:str]
sops:
    age:
        - recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTHRsbHpTQXpFNEI1eVBP
            aFFTQnMxKzAzNUlCck9KN3IzMEhxNnAxV1RVCkNKaDRPTUNLV3JyOGFMVlBSZUFT
            S3hTQXNuUTBibE94ZnZ3MVlzRDAxWjAKLS0tIDI1NzhDY2xDVTFaOVJBUVpDNDBM
            dktHbmx6UjNncGVEOFJWNUx4a25BVUUKTCXupBFixAwNljDBJqoRp0oN97/SJQXM
            a0G8b/ZsvxSQxvKOjQGQVakyoGr1sudNU1BA4tJ7GLPaUL0d8N2a0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T12:50:39Z"
    mac: ENC[AES256_GCM,data:mfFt6vmCLEO6hD9ahG8beJalgCKKqtZw46ZpTprs3oOxw/2omr6WLETT0zvfECu2t1jAbqlJso3PJ76u6UYMlcpS+LNP0C4az0qVP/VCq8Ocrff9TU9OFoJBjaa4XiCamozXXbfhyfNC0N5oFmfEzDu8/MpPxL84Obic5m92ml8=,iv:93v9Laj5wSSSm7cYmALYqazFyFrc0ofgA7wKOw+6s14=,tag:hJj6+MC1l/hJp7z1KNj/kA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: dockerhub-pull
    namespace: portfolio
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:nTnWLHHhuRV4OWFWar4epd43EAghQfGlxBcowTxvDLAlEvO/z5MFnjL0PrjIFvzJqMHQlpbNG6MYsFEwA6h5r/QavvRLEqXuNYmWh9C5CQs8oUiCn32C24wSwqBliC9HPP4/hmK2qHVnZ79YNbcH2ZIRNWnM,iv:DHGVJfQq+cBH4soYCOSRYgVLo+njV4/ahRSGnhVgfjM=,tag:adGHvtvpQY2DFj49dz5Lgg==,type:str]
sops:
    age:
        - recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTHRsbHpTQXpFNEI1eVBP
            aFFTQnMxKzAzNUlCck9KN3IzMEhxNnAxV1RVCkNKaDRPTUNLV3JyOGFMVlBSZUFT
            S3hTQXNuUTBibE94ZnZ3MVlzRDAxWjAKLS0tIDI1NzhDY2xDVTFaOVJBUVpDNDBM
            dktHbmx6UjNncGVEOFJWNUx4a25BVUUKTCXupBFixAwNljDBJqoRp0oN97/SJQXM
            a0G8b/ZsvxSQxvKOjQGQVakyoGr1sudNU1BA4tJ7GLPaUL0d8N2a0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T12:50:39Z"
    mac: ENC[AES256_GCM,data:mfFt6vmCLEO6hD9ahG8beJalgCKKqtZw46ZpTprs3oOxw/2omr6WLETT0zvfECu2t1jAbqlJso3PJ76u6UYMlcpS+LNP0C4az0qVP/VCq8Ocrff9TU9OFoJBjaa4XiCamozXXbfhyfNC0N5oFmfEzDu8/MpPxL84Obic5m92ml8=,iv:93v9Laj5wSSSm7cYmALYqazFyFrc0ofgA7wKOw+6s14=,tag:hJj6+MC1l/hJp7z1KNj/kA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
