# ENCRYPT WITH: sops --encrypt --in-place 12-secret.sops.yaml
# sops will use the .sops.yaml config in the repo root if present, or specify --gcp-kms
apiVersion: v1
kind: Secret
metadata:
  name: portfolio-db-credentials
  namespace: portfolio
stringData:
  uri: "postgresql://portfolio:CHANGE_ME@portfolio-db-rw:5432/portfolio"
---
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-pull
  namespace: portfolio
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{"auths":{"https://index.docker.io/v1/":{"username":"jochristian","password":"CHANGE_ME","auth":"CHANGE_ME_BASE64"}}}'
