apiVersion: v1
kind: Secret
metadata:
    name: renovate-secret
type: Opaque
stringData:
    #ENC[AES256_GCM,data:5rWwk1/KyXhuo/tokhNwxmMVKL8+p6J4njA9kfHjpTxPUo53qDCDc4LbdYdu4pRtD5wXToc4+uGVy4y/2xoHSkZJgjrv1GrM,iv:6X+4mwpqwgi9XpitJ/uGi5UrSBU6ToFPDIQ7UhbN6ZI=,tag:I5Xs+rQllRkITCmB1NP7xg==,type:comment]
    #ENC[AES256_GCM,data:BbhfMT0sYYOlDvMohC+thYt6Wta8qTDTzECN1ZLZONnTXftTZh4gk7A1lwucfdGPeeXXxkg=,iv:VHNmU0gaTJuD4WinNRmar3q/WsVs20GxZBSuYO6qDiI=,tag:m/Ebip5HLtJZiI0bLRBkxA==,type:comment]
    #ENC[AES256_GCM,data:vDVVP9rtHJ+y0ISKaWWpBeSaFVJEP1m6qaSrlNeLbr7Eql8SXWqKY4WptXI8MFnkxrYvG9OKhZ9O,iv:D53ScB7jAkKhXHzmpr/kNs5eyBwP57TWmYy6I1h4IdE=,tag:Wpqqc3LJAsI0eCZP27CTbw==,type:comment]
    #ENC[AES256_GCM,data:SWNdM9ot4/NDmVvIbVOgNm+KOaNpBP5+e4s5ggKvAs4KeQbbcHW7Lj71uW/6hXy16axiM+Ixv9gU13uMj7skVQ4t3JwUh5iBz+iYnfSpVM0=,iv:3TvlcF07VsfsrE+xn6/1TxAJVxMUKfuRuJIYX1Zr6ow=,tag:Ba6q7wKzPITxqtVsPgwEgQ==,type:comment]
    #ENC[AES256_GCM,data:yYmN9dnbCyxCJ9Y4BZVRVhWSTRpO3TAiJOQGy+e3aKb1Si+HTAOSXdkRaX/AWZ3e31Dh8FQ2DIt4ORLpEHEtnaL6ycH+IV6/dbHHforSMhXj81Qx,iv:R2juoVUu2zaXYQBhXBhm21KIIhHTQVTyTcdmiPahkck=,tag:B4cKVQYfospWA6R3XXcfmg==,type:comment]
    #ENC[AES256_GCM,data:TQ8v42iHmIFjN/3+3RzkCVL4CZsINsv5PePFZM6VfkMlLL2DAtMfcy9mBuIAgFJAN+PJ0ZnW/akOMOquDrshMgs=,iv:NmThZ9+oZ9st47VpcTOU9Yi2Q/hQgAT6gP26jtpo++I=,tag:mFLsXvAY/9LDIfYeg5ZioQ==,type:comment]
    #ENC[AES256_GCM,data:Q+iri+ml1+XHKRUtQ8a/KMXBiQYMYjn+3FIDAEvf6OPc4L+HvtWy+ELevlP4lgpN,iv:M4ZmmHA2dQN5yJWb82ndtatGz9iAAyqzBpSsQxmFFok=,tag:BSksUhWEUv3Cj3XPNV6Q3g==,type:comment]
    #ENC[AES256_GCM,data:TQppyNL09ABSBb6S3zmutnM6D/yiCvgUQyihwEVH/1XIaQlZrPuyUsALpFmfHE5CMAQstBLOhQk24iaV3Y0=,iv:3xTsAgRHCjnjzzzdXiHtbl5/mM/xAHq5nB8yZ9836W0=,tag:+Gwt2IW+2WEmci+zBF/WxQ==,type:comment]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:ajYkWPzJj+DI/X0+ALYQVuBZZgtpfYl0R9tGp1Evgwbo6tszTsn2ebAwCXaI0R1otHwv7ZRm/AVFIHbpQOlLgKGHbNszSctWbXMneW4Oqctu8kkRtSb2A2rOIaRr,iv:xLhuOh47d4kIlQutNYLi2/aqsphBpM8i4Wi0pCJpESY=,tag:TPlTL3e3WTjopAbbKpPH1Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjNGxZZ0F2K3BOUkQxMk9u
            MFVEZkxEcDdZZmg4N2o0aWpoZlIvaExWamtJCjA1bzZ5eEtpaW1WcHZhLzRHVEtr
            aHNDaExiNzVlL2xHb25oRHRWRlpKZDAKLS0tIGlHblhid1NYL2xWYWpQSlJudndy
            OExaek5WUWl3cFBWRXV6a2d1TzJST0EK/QeMUTvpLPIZ5dgPNzyWg9Sk5RuVJa3R
            fb/zLHehLAbbtQO5Bel0onmvUsf+UI23/oj0Z1DHKjoSqhIQR6+9yQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-23T18:27:23Z"
    mac: ENC[AES256_GCM,data:coYWkvdLzaiBIQsrFRZ16BHBvHCwug3XZ0BayhSJ7jlJxKIq5PGuA0dsoQATExBYinYLDCyXlTY9t6dvKCyrHtiHBKWvFMo5+uIpMNbI70W2Lc+gEmouon016zfqq/CbTs7exJvRyV0WK7HBB5f0jkil4lae4Ud/Tq+U+kIZ+6o=,iv:1rsbRxVvbI6MmOSaFFygN4Q7OUnlui0nVIeJOS1NFZg=,tag:+rW9vln1J78F+cg1ywc5uQ==,type:str]
    version: 3.13.1
