apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: renovate-forgejo-secret-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - 02-secret-forgejo.sops.yaml
