apiVersion: v1
kind: Secret
metadata:
    name: renovate-forgejo-secret
    namespace: monitoring
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:db3JeAaBXWOB0auFG5XZvN0yqzSdYcidOZipjm12ihcXdGZeqyXa7g==,iv:GkcPdIr/6FAe0qQSpJmAGgtYtGxYiV48qKmRJWL6DsE=,tag:I2djcnXUDgm1TTo5aDuVBQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzcnNjcXdrRWR6cXp4S3Bu
            Tk4rbi9GMHN4KzRuVmFyYWFsL3poM0NRVkZRClNNa2J2eklEYWwyUis2SVRoYzEw
            L054L2ZuWHgrODBJcFh1ejJDQXBqNEUKLS0tIGx6NTZMN0hxQ01LZDhBYUc5NDBs
            UHQ5d3pCcTRGMHNYaUNWTXRScndvYjQKmA6fVimYapKjKWtKs9BxpXp0DSL2to4s
            Eq06+OxWzH2/A+VEsZeCfg2v1xGsAhrRH7C64mJsMBcXGKAdUialRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T20:37:59Z"
    mac: ENC[AES256_GCM,data:smRBMPjkrd1k1D+oYYM1oRq+X9u8WY4bqra1bZtrTVmzTx9yNHDsiIPZVB6UvDE2ar02J+D51/LeEDkEJ5xckGMrz6r2+BbN2gNk8ugKrbWpwdbSZIdT6BAEDSZ5c05jAtXYOTIPLDMd0Yy+9HAGaC8kU6E3Vg3cHGFduogzvxA=,iv:UL/frl+stZ0JUkyeFhJzfw/ms/KJVbLAeg2bAgmD2NE=,tag:8D4262Iy8v27rkrs2O9C0A==,type:str]
    version: 3.13.3
