apiVersion: v1
kind: Secret
metadata:
    name: renovate-forgejo-secret
    namespace: monitoring
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:nbMA5uyrSdED3IckYTJorYOX2IYNI+cta1Z0zuep4Zo4MpmxSbYHgQ==,iv:hP4RZse0nfEegEtHxj9xTchJpQ+NyW7Velp0xL/+4FI=,tag:wUefGiBxYXdNsyvOXTqvzw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWHpvRjhBazNtaHVsSzU4
            K2p5dm9lb3oyVTlZMExnT1BnQVp0Yy9WclFRCmJrL2pxU014VkFWQ2x1NWt1endm
            UkNFYVcrdXpkelJzMy9rVUkxalpEVUUKLS0tIFQrelVyRVRHZGxRZnlRVnR5T3ha
            SFNsVDZ2ckxPbkE0NTFEWUZZWTk0SlkKnNpQbdO6kRHoNKUg26kcd+Fok0Ptc2ss
            0+yG97dBuwcyjowC+ZM54cVokeO8ouR5EgySr6+5XAL9NtDkXydWzg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T20:14:03Z"
    mac: ENC[AES256_GCM,data:Uy+P7g1fnLtRXtJVc3wb3LkKLLGBUZQVOwWpJeY7+ibrDx8GCicswlGcL1E7OEuaNsC/BP7e4czZTOQHsbktEEFyb5jKyMmhFg9nrpHAclTN5ofGJdfLkPHNEvX86ExtG5iyBQObuh2OCeDAm8251y5KTtM9op42TqFnqUq6xq0=,iv:s4J8CbEucqtROU19mYkjX9H5M4XpyUpBNf3AP6buwrE=,tag:tpPzC9Z3l/D4pGlE2gLh+w==,type:str]
    version: 3.13.3
