apiVersion: v1
kind: Secret
metadata:
    name: gluetun-vpn
    namespace: media
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:ZOfqGtQxPR4jtc7Y9GC9E7JeVnGyyhsnK3OkxsStYepTMxTT3YnGeeUGcFs=,iv:aPym2U+z1YDkxfFrPEFQpBxBiPHaSWTrHY0Iy/y95mo=,tag:3s+FyOk1Td0otXNUp0i3xQ==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:DLj00VScPHdlz0A=,iv:lwFkglcRZ849Eij/A33zdcLEOnUqb6Uy9tGrP7fSRWM=,tag:EK59458npNXsXM9a436p4A==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:S4A3vWlBOsaDRTi5JK0Wc0AGRSvmVNAP4jIm+LURUlxqR7+qtnfq6y+8nUk=,iv:JfHdcm/dgOflz9eOM20SWRxdRGiGbO2P21US5lvVOtk=,tag:KFILDvfKn+wM6pleWudndA==,type:str]
    VPN_ENDPOINT_IP: ENC[AES256_GCM,data:ongaBktdcvIg4ZaChrk=,iv:pYs48aD/AhtqJmJFOCY7uNNyhNeyCdANsIwfpzOZMrQ=,tag:r+o5+J/ZGxyayHQgklFSJg==,type:str]
    VPN_ENDPOINT_PORT: ENC[AES256_GCM,data:SmVI64I=,iv:cHScg8qKwcOzSsWYjmOouhTW4i/M8DOB2i7jx/yvPAw=,tag:at5aNqJ/B92yVPVjcaT/hQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjaStvbFN6TDVXSjZqenNF
            NjlWdVpLV1dhQjduaHVvb1hYYnpSS05DZFZ3CkdBa0s5ZXNTcUVqb3RjRlh5SGU3
            Y3R2VVMyY1VRVWppOHhnTmd1dEh1MncKLS0tIEcyYU5EYm11dFZ2aGRPK1FMMjU4
            VXRhYnhtbE53cUcxTndNMk9RWWlMYTQKI5cydkSS6Ak+XdBlGAA0YSv7sXiCzJRt
            ImBEcMy4Unrm8/ylyToEJvuOyg1633n93dDrU4J2Pyg2ZJn3iixQnw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T20:08:14Z"
    mac: ENC[AES256_GCM,data:xztXwOH4q6hQqfwgHzkEV7PP6HWEDRzKIUVWSyjUdSENcrfdxCoLiJ5EacmFyBDEmkuXb8Y7LzaJdlzMeuZYm69iCcjEysReMJUbXtdwhvO0FyHRLRc2aWW/zddJRu6TipgZH6BsoCfq0F5vFs0W+F00ESOD9dZSB5J167HGVN4=,iv:dbuRHg08sJcFqIghkJibVmexMuUQXphBKCDFRaXrsA4=,tag:mJB5Nhv7ONXj4mGY97IsFQ==,type:str]
    version: 3.13.2
