apiVersion: v1
kind: Secret
metadata:
    name: unpackerr-apikeys
    namespace: media
type: Opaque
stringData:
    UN_SONARR_0_API_KEY: ENC[AES256_GCM,data:nfjCWkMKIf82p92EVH56Jl/efIhF6/S7X+lmxzA=,iv:3jrVO89S0hhqQJ2BNES/blmxTBYPI2CwdU/UzDd3TbQ=,tag:5+4TJRRuGxg6ndz7hsHEJA==,type:str]
    UN_RADARR_0_API_KEY: ENC[AES256_GCM,data:HoXSGjSVAzMLSshYs0t7Bix7ShcVYkQGfoHpUm8=,iv:CEon0WDbWywykV/SCIrYdSndRw0mIEuzrFSaAsD++z0=,tag:XWxBwKdyR0+tWofSdyoCjQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSGFkNGdGZFFuaG1ZcUJ4
            VloxOEtWUkR0RC9SMDg4WmQzbkkrYUlLd1JJCllVb2VWcVJtOEtQS2ZadHVzWkFy
            QUdPMUZSWkVZWTNiQ1hQNXRzZ2NGRG8KLS0tIEd1c1ZjaTkrVlJ0U1NYR0xESExk
            MUw0akpndnUyeGJNLzV3SVpaM0NsY1EKxPkj2yo22RbroneKlCQOTdAbtjyVTh4c
            GPo71skU0AJ48+U69S8J7co9GoXpkIUeEUyKNQC99/JyF9k2+mfFwQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T20:01:01Z"
    mac: ENC[AES256_GCM,data:2VVpJq0kfdnQpY0bWKtsY6LYyvYVgNYlmwYyB5mafTrl+13vspD8cCcxf5wMhXr44S0teLMFB0bZ55sASkUZHcLX9OCHhC8TmxF6HEee1kFb/fZgkxQbY9qckKLAL+NJVSUF3IZKomxNx6L6QwchoIfTI+yhtnZ21Bp394cqxY0=,iv:JM3jxShexbwHkE8VKy8RU4xHqDX28KfXocsP5JP2uWA=,tag:cpbP1Xw2VnePTRTJTcbuKQ==,type:str]
    version: 3.13.2
