apiVersion: v1
kind: Secret
metadata:
    name: unpackerr-apikeys
    namespace: media
type: Opaque
stringData:
    #ENC[AES256_GCM,data:KKBHYYGgsFKjbMgwoWZEnqi4FlxaSapHRz6sfEfqULbwC3XEfAKV6BzZmOF3hkSxF1DMVXqayeXBGLGDKPtsEwdHY00MQ40=,iv:8oGQSE0RJicVgFqcNXrkdbgpnogpR4Z8S7tzTK8KOi8=,tag:ghqFWuHRDp6Jz1YbqIx0dQ==,type:comment]
    #ENC[AES256_GCM,data:QzjSraFoEWTcbCN+jKiqo3DT1jdYsEQk68N/DBbPJN73qpCzMqDZPtQMNS6Juv2njbctaX3hYoILjXoYJrDvbUkGD0I3,iv:hzR9vFB0LUGfd9+uwTJgrp8WJtkQxUVbqjLIxUak8co=,tag:IqXpPc3klJ2Q57YGA5AseA==,type:comment]
    UN_SONARR_0_API_KEY: ENC[AES256_GCM,data:puNXc34BBMOFzwG+d/tSDROpXD5MiY8o0BxIVOc1HO4=,iv:gs2HUPF5QhLXJ3mtemQuCmdz9nr0tXiajVqPkRNFtqM=,tag:gMoVikvoKsc3BsWK/5sWPA==,type:str]
    UN_RADARR_0_API_KEY: ENC[AES256_GCM,data:xmG4t5vq65rif/wxfJHukPjGJS9D6qzTjIdn8/lrrNo=,iv:8C6dQJLnFYoh1aerlOSum4D4BCdJ835XtedJPG3QGPg=,tag:74oaYiA4lATQWtXSqw3jDQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UHhWenBxTGkrZ0s4MnNl
            ZGZWSFJKc1IwVU1LMW9yS2wvNHdzLzNLZnljCmxHTGZFSkFMbjhOeHdQSWdsSmJU
            K0VKOHVlR2NVNXFzcWpyN2l6WTVJMFkKLS0tICs1c3hrbjJYczY2M3JOcCsyOFBz
            RnR0a09EbDg2eVF4Ylk3TmxhNUVJaFUKqVPZaglvDwsC9Fb3gKX/76rY4DcHx273
            psRt7TtXxFGunOHnw+3CtHCoVgB/Q5rwm3L4oAhlPaBRAwzYD/3XrQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T20:17:37Z"
    mac: ENC[AES256_GCM,data:oBlGdUheecTmOoAOGgjdWwtN8wZegE+KJUrx/eGroRi5djoCL6gulhf/7M4hKcTYEzSnFabFr5wiiISSOnz1Qrfa8fbcYPxfyuOGAakd6/7zNQIyGLaiVXT4/82JbsaR1zvPJhW5LlsnpAMf+2lsovQRglkU9sedtcSTu09x4Sk=,iv:gO5kCwJcACdzMHKdukDuGkDJQcsZ/v/kE2ERoZsRx4w=,tag:AYY1nGIQSJPNZlhDLtOy5A==,type:str]
    version: 3.13.2
