apiVersion: v1
kind: Secret
metadata:
    name: unpackerr-apikeys
    namespace: media
type: Opaque
stringData:
    UN_SONARR_0_API_KEY: ENC[AES256_GCM,data:+j4lbrw/zWAiHi9e7ZPkVV6eS6IeWLoAjiVIPHYXxzo=,iv:1Tj/T6KZWoT5/14u9UMj7WW7REOI7dzQn97gneeIf5c=,tag:NmbuRFsM8ZX9siH+etgURw==,type:str]
    UN_RADARR_0_API_KEY: ENC[AES256_GCM,data:ce0x2fBmlRfwF5eDqKluz1nh64zCFni+yncEfdWnfOY=,iv:yMZfeGoHmWxa1TGvCNnpTaTel6s7Tg5Ss83RiQ+LSfY=,tag:tZo/gx3K0kQHaCrez7QqDQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNmpzbVZOTStmMCtrVFZw
            bDFNak9YbHBSWkRyb3JIcHprQmZKNDVMV1VnCkIzVzlLVjlHc2ZRVW1EME1rUWl0
            dW9sbEkzeVBoRDNERjR5b1lDV2JLUWcKLS0tIHdVdllXNGZiQWg2S1IwOVZjcEta
            dFlYRlAzYytuV2E3ZHUvVDF1YkdZOE0KLSUi2N8GkKLFyGJN4kHsv7UawqdpnUiP
            0x4ElwcRj2N9TBEFcQe55mspiFVefaUnmyVZGmnazS/xu+g2rQ3MaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-19T17:24:17Z"
    mac: ENC[AES256_GCM,data:tS4Hgll3ai0cYrIU+PU9aKXcG475QX9nBQl4ramC9AJzYRC75jDol1ikNYLEqUP5GLS5dx/k5erZnbQwcwwAghApyd9Cen4+enc+y3IuVJql62Djzy42gNl61Ejz1fhkssdP4XVaqwVbCdBc+S+FPfBKXT6P7UfPa3Vr5nKPvIA=,iv:o7kr1AHd5+lK9oYKmd10oxahSsrhf7AmSi056YoUDj4=,tag:GERZ2HtSZD6V1PqgP+v6rQ==,type:str]
    version: 3.13.2
