apiVersion: v1
kind: Secret
metadata:
    name: s3-backup-hetzner-qbittorrent
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:7x5gb0MG4z+cA0fNmWq3wwLCfogWpuJZrbT/qipi5CWE2Lb8sNZxJGk9mL/Hmc6CM3Vz8L3iLzRSY+xixFS248Gm7vBaVm/D+/6tXo3d4Le2tg==,iv:TELjSsWjU7hlzdmOI7Ywx3/Bei0H7G3F6Mwsh7XaOiU=,tag:ytLysYPTPhTmQ7/M0amh0g==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:EeE6btyrfNw2mnGzY5qNaUwl0wkOJ/OznaVRw0wB/kIieILdcZoalbGpx5o=,iv:P5U8XHDpFEJQr/yGlro4RupZJWTnSJYdiRi/3kzOel0=,tag:V7ze6xNTZYGXLN2Qc4nfGg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:lPVkyFfCJ512LSa7/gssh2KEhzs=,iv:k9ei8fDYT/NzNs5GYQ0h/0FyDcu97ZTelOIcrb0eVJE=,tag:mW5aeiYi2nQSZXUbDOBxKw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:QPa4F/ulXvhkZeUK3TMCey0W6vDu73nssGNUJZqj2Hrxo1kW7SlpCg==,iv:aRidI3iIu+LWUbASDYvQ88X5IZqDmBt0mSKPNJd7PbQ=,tag:rUktX1FmiV/oO8MNF9yI8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByclE1bTZMR0NidXQrQkph
            UUZWdW9rUWRFVWIwQTZ0NlFnNDNXRjRQR2tFCllQWW5mcFdreHRJSnEwbXpuWTBQ
            UVA1aE81WC9Nc2JGRURadE14UEFHbGcKLS0tIEhIajRjNHFOdXA1UzVDSkFFdXBr
            ejZndjRvUFRDYmZBTWFCdngvQkJOem8KTUWRFAyoRjYtF2LHHqNr0HtOLCQyvoee
            evSuRglibHUHWbV7rAmTs2JjPBLOpMSmZbTsylztywxRoOz9A4D9Dg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T10:44:29Z"
    mac: ENC[AES256_GCM,data:pXpaN3awb0ZcWxViadw6LCQpl8ryiRzWtyPmrEBe5m56Qg9BXfSMAAqt3GIWw5Kz36SEZ6gZLDvj9p5UErY0JOBVmLoE9lpqN/xYrGDu6Ap0yZFrJ7i+/wYnSbZqB3RfyoGR9s5eEThQocKY8OXscFeZABkNsv4ST4p+46jKzro=,iv:GJUzE2Ami2nHOgknFMwtbYd6kVzZFnhjVl72cZB642M=,tag:+gvD1y7DWZN/Y+dYwZ1gHg==,type:str]
    version: 3.13.2
