apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: qbittorrent-volsync-secret-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - 03-volsync-secret.sops.yaml
