apiVersion: v1
kind: Secret
metadata:
    name: s3-backup-hetzner-qbittorrent
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:7x5gb0MG4z+cA0fNmWq3wwLCfogWpuJZrbT/qipi5CWE2Lb8sNZxJGk9mL/Hmc6CM3Vz8L3iLzRSY+xixFS248Gm7vBaVm/D+/6tXo3d4Le2tg==,iv:TELjSsWjU7hlzdmOI7Ywx3/Bei0H7G3F6Mwsh7XaOiU=,tag:ytLysYPTPhTmQ7/M0amh0g==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:EeE6btyrfNw2mnGzY5qNaUwl0wkOJ/OznaVRw0wB/kIieILdcZoalbGpx5o=,iv:P5U8XHDpFEJQr/yGlro4RupZJWTnSJYdiRi/3kzOel0=,tag:V7ze6xNTZYGXLN2Qc4nfGg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:yn2+c8UFcVVRx5OV1CuIOvEeOWA=,iv:xDGq+HCkLie/sllWLtv5u5DSbqEjPxkBK875rkUHjSg=,tag:GMAKDBX1w1bAdhsNGR5IFg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:RTL2zwaJQH7tjdG5vNGp4kvcrsOacNo5ZsZt1wvZetZueIUZiz9Lgw==,iv:eRp9Oii0j8kma6BhrLy3HNwTkeOGcG6xa6yassJ9UPg=,tag:KcSajHIHD2KtKb1oqaUsRA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByclE1bTZMR0NidXQrQkph
            UUZWdW9rUWRFVWIwQTZ0NlFnNDNXRjRQR2tFCllQWW5mcFdreHRJSnEwbXpuWTBQ
            UVA1aE81WC9Nc2JGRURadE14UEFHbGcKLS0tIEhIajRjNHFOdXA1UzVDSkFFdXBr
            ejZndjRvUFRDYmZBTWFCdngvQkJOem8KTUWRFAyoRjYtF2LHHqNr0HtOLCQyvoee
            evSuRglibHUHWbV7rAmTs2JjPBLOpMSmZbTsylztywxRoOz9A4D9Dg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T09:57:11Z"
    mac: ENC[AES256_GCM,data:tCKfEN4dD2yZ8xEpgh0d60/R2vF1F/21q/xAFFq3WxY6GdRpA67ZUG7e8TKwpDmz8isEmVYULXGxd4jI+EWLh2DHX515gPWHoPPweI4uihX+Mz/QDzGahfwzUmmMc1PfmhaYBRvFcThuc0UsCUCZBvVxzJuH8ba6AOLIuJTNRbc=,iv:DdqAtYw9itBk13rJlJ7KCYJaXwu4CC5eMmDtQRy4QN8=,tag:oS2j9MWb+Rq7CQdGIGCnPw==,type:str]
    version: 3.13.2
