apiVersion: v1
kind: Secret
metadata:
    name: patchmon-secret
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:Z1jviHRj3oqeCO/qbuNtydx5w+xx9O3cI+Jrna7+2eah4JDXpsfJtZ/5R065KnHB8vHUN4SYEXCF0JbY/CEj9W1rUUMxwL6hrQuL8W+UDyFZt8biCNzlljFhMrdDgihDx1ud3mwQs+ZhtUFjI2jKCnOhD/oObDYp1RTuRQ73ars=,iv:Ffm9+nQ52SsuCY6pGAmc6CnXRiAYR1nQ26FUUlDwiLk=,tag:D2qgieo3pizGebxSEfCkXw==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:jfpY0u0bTrjgnPVMiBcRgOIrE/yP5CmE9JZXZ/ckWTrwexq4t37SwYcgaPYsVfv7+S0Yb0n5wAsD6uAxLyrq7mRwMT9YSMARMkUX7NBvogDZ/fbBYP+FnNMvYUulY4olly/f2GcYer4WUD4VEROc2HoSfdqaggjel4Utf2R9JtY=,iv:bMv/mrBELJvTQ6qQ9pONGPNAJkWZ/uDoQ54h2I5nxwM=,tag:mRFznod0rs4fmRZNvBCaMQ==,type:str]
    AI_ENCRYPTION_KEY: ENC[AES256_GCM,data:F1bz0AIDo1a7rqp3FcU3UB350pQs9lWTpPSF3tNbwI79SP5395nebwLZuQuRbILQLAyodNsVwHAGPl+8tSmXDg==,iv:7DAIUE3ZJhMKWf5FWhPUlINzimx1XpVmHO3RNvc0DQo=,tag:iy1o1/lBChbiKwrmyiyjUQ==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:aIVR4lEbjJ1NNQroNLmBBkzPGVejYvIcWcPjLLemUFJQpG2NvMwIzea10okKy0m/D+z/1/hM8WDRN3ZBcz/D2A==,iv:q5qonDVcgkPjYt+WWav9hvFF6+LwMxw3FwuBKDaH10E=,tag:c4cK+dy5UbNZeHpOB4DWyA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Lzg0a1lvRy9Ua296YWJv
            NExaZUNHOWViTUN6Q0laTUhGc1JpVVhHU1ZZCmdRRmllVFZZaXluRHlIYjBFMXRY
            ZS9obWtmM2k2Y0R6eTRkVUJPT1JTck0KLS0tIHptbm1QSWVsRlcwbFFaaDcxWi9M
            VzJ5QWd3OEE3djlzTlZ3Z1hQNmdyRHcK+jTrklKZ/UlJbngIBg+qiJQr079UvpFw
            iAwPprkuwTiPByEqVGGJSP4TBS+BSOsqXfPuUw5ZdQQlY0OQZezVGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-30T12:38:34Z"
    mac: ENC[AES256_GCM,data:j+1QGqFluYYkf59maMxWFQAGmXEXT9R7xwM8TQrFSUtiEnxVbc4at0XAwVPlZrp8P/mZPtV6jjcG2inSH+OtupzvR75+awJPNeZK0EHYbvk5/MpZvrCw1DpqGIlEwk8EVLMxbi09R1te+aru11eXNAyE8P9/rpfN1MIE0jesPgc=,iv:+G5tPY43khM1CceFyFbUxycRIp3FzLykDHRQQIQ9CSk=,tag:vOeEtHsWT3hHLgLu41JD1A==,type:str]
    version: 3.13.3
