apiVersion: v1
kind: Secret
metadata:
    name: patchmon-valkey-config
type: Opaque
stringData:
    valkey.conf: ENC[AES256_GCM,data:CTzVLS9eJbv0diMFA8OyyvVIMpP1eynl2nFBdptqvryMzqWBWducXtrOwRyuHcjKIXQDAM/DF6mROFigiGB1IXq74s2GL/1JDBJmxM8X4H862IvB9fiX4fTYjdqd78QYY8WbMAX1,iv:1vrOfO8YRxGp5H8z4ss0DCOgwqFr2YZVQGysv5/YW2s=,tag:aQ++gw7NQQrLP3IfIGpuBw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRFpvYUxzdXE4NkdaSnZJ
            Z2I4NEtWMlpBc3R2T3pHUDZKTEc2QkZZS0RjClRtcGhSbUZMQ1lmbUhiUTFENnRu
            Yk5IOWxwOHB2aW1jR25FTjFSQThET3cKLS0tIGg5T25HalNoN1JFMVlnWXBGN0Ru
            K3Vubmx6MUNROXJQUUIreHNnRDVMZ2cK15b/aJ9JH7lIBDwwqLZDSGAjk81EiXh2
            2JpVR+zKFOiKhTNT3orBUbvjPYC/5tYAi8movfj+r0an6S4cNUVQGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-30T12:38:34Z"
    mac: ENC[AES256_GCM,data:G9XestWswdqYpzpUPDob+Ao5i/lydYxMwO7j8XmZTCROCzJBxlPH4mAm2dWcTQYHS78J/0hT+vmkEq4xmEfFzFJLIUVxBAUWT/RuY/e19fodcQDOMGudNQIg4ZOdDBIUaY7SnrSwXAj0EvMctA2lzenLZPEtr4etFjTbE65NXho=,iv:AHaap9PIoVRwLRUj8o6M+YV/H44Al1acZ4sTUd3fLdo=,tag:XQJiOobCjqNpZe+FUc2ubg==,type:str]
    version: 3.13.3
