apiVersion: v1
kind: Secret
metadata:
    name: s3-backup-hetzner-patchmon
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:TiHx6rID3z2dYuQdFIPjM2GWeOFBpy8P7IeQfJlbREBWjKslrqwRT8Fd/fCkbw4XYG1bgDMtgyle+uHzhE9XEcZfe6IzyWDmUoVl,iv:Qc1gz2/kfAShuiv9yFswe4Bwdjq8YkOA/tsmGF3+Zww=,tag:5rOChGkzIpZI/QO8ycIx7A==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:35Phvyv2aERGIyelrc78TRhTxF0W7yIjQ5ze2Lrp83Ce+vSbiyCCFjtiok4c/8WEnpSuPblln1CsQcxmJz2yIQ==,iv:UNY8UaYXzSMcJG/bKU4iSw0xvkkkpLyct9DB2CIXNFg=,tag:ZdOnlntdUqgvlJFoO9EpfQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:inMjr4uy3d2+PWAdcGgLwlpLC+E=,iv:ovNkrs1dYEaRuXpEwCvwcU4PonqSHpWC8tpCL2I1O+A=,tag:glW9DtL3IB6OmDzNVYcv7Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:DGkMAF6KaVx65QFswDcQUJxISIheegJLGSI2CsGakEVFn2x5buwvYQ==,iv:07pdkCI7zyxXcggWZOAZL1+b13MT9D070RJiOD3biFc=,tag:P5aHaHTeixAsaXYhr69s/w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwOE1DeGxmT3BCbEh3R1Nh
            blV6dThJMGZpYXJMZXBqclcwVDd5MFc3UVZzCmV4ekc0L1ZSTFNrbWhBbEdZZmJi
            bUxVUnRmV3FVdmZyS1lnMEtLODNRQkUKLS0tIDNwa0VOZmtINWJQVHJBYnlOVVo4
            bkNaNTkzWnVRcG1nVnE5TWJFK0NrWWMKSBDM7ELO9OYw4sTx/qaqGFcH2eRe2Xfq
            LZUizNlcnxvcClIvSi95kyjHyxhDtwuTZWpRj1dV2GIM0sNxXTasUg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-30T18:34:22Z"
    mac: ENC[AES256_GCM,data:j9UKFcVt2bLOC+VQirwpRxS9BuhaA6TeHkHP95yy2dA0cqNIhEZKa2rVZeOAJBoyXbSu5f7pL678zxCHVz4z1QkFgZHfOYznff6pKh7BDjNUeySslLZMVg4NE2PmiBtty7R04kO42iMjvvPifq/nQxoZJu1xm1WcIAwAlOiSwyA=,iv:dbbUnh/o0gl7SyzHPrQFeTwo3pFc86syyDoZox9pUAE=,tag:KQnC4cAyFrBrA0yPIacLTA==,type:str]
    version: 3.13.3
