apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: patchmon

generators:
  - 01-secret.yaml
  - 20-valkey-secret.yaml

resources:
  - 02-configmap.yaml
  - 10-cnpg-cluster.yaml
  - 21-valkey-pvc.yaml
  - 22-valkey-deployment.yaml
  - 23-valkey-service.yaml
  - 30-deployment.yaml
  - 31-service.yaml

images:
  - name: valkey/valkey
    newTag: "9.1-alpine" # renovate: docker=valkey/valkey
  - name: ghcr.io/patchmon/patchmon-server
    newTag: "2.0.2" # renovate: docker=ghcr.io/patchmon/patchmon-server

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: patchmon
