apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: patchmon

generators:
  - 01-secret.yaml
  - 20-valkey-secret.yaml

resources: []

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: patchmon
