apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: yamtrack-secret-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - 01-secret.sops.yaml
