apiVersion: v1
kind: Secret
metadata:
    name: yamtrack-secret
type: Opaque
stringData:
    #ENC[AES256_GCM,data:w6kNsIn+Qv0MQJOWlCNYx23rJgSv,iv:y747Xi7y+sJXXso4xzOpgEP9klG9EcJnbRf27of1ATo=,tag:3G0UaWAxcwkwSiUa5xbhRw==,type:comment]
    #ENC[AES256_GCM,data:6isY8f+DhOMJoloJIe3EZASA2xH1UIVxRkYQA0OS5Nv7l4tTW7VoRA==,iv:YenMdce6+F7R2rGuMre6/VMqoC06EIGwL75ri1PUakU=,tag:iRg1OSgQNsKYtIo6rL+pmw==,type:comment]
    APP_SECRET: ENC[AES256_GCM,data:Q74CExM1ooQ3zEFPFICKSsNF0l+cHg4dfmcbriaCHnKbQEy3+qf7WciGXfI=,iv:GxkWBysFolt4xe0PzSjTenYXEzzp1rEVW6qlhhJP4qQ=,tag:IFpv/baITdlyCn3XEnkwpg==,type:str]
    #ENC[AES256_GCM,data:IXynPRjILabVh8F9ZZzSi13h+jVmFkYYH5kylMZ2,iv:7NDjCmpJueti+zBwiJ5Bt1jldgGqYvPAb1X6nqPFBN4=,tag:reZBa+RmaSWwi63viic34g==,type:comment]
    DB_PASSWORD: ENC[AES256_GCM,data:EdNjhIyKA1Fq6ctZIrA=,iv:qtLS8Ldr/ctxby4VyNwq7RpChgnkRa7TeFf+aBAHjJk=,tag:Y/DWnZULbJ1fSrEFlTzvKQ==,type:str]
    TMDB_API: ENC[AES256_GCM,data:w3LROB9+QAfEQaV/2vgEf4dFrZme7gKVE4WNZa84t00=,iv:dypylVty0MzHx5sm0Uj86TAzSs2J798ZE//Wb+zuan0=,tag:IRr+VcfG0TS5kY/ooKimdw==,type:str]
sops:
    age:
        - recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSmp6ODFnUVg5b0JpaHBL
            NzZwUThFU0V6Z1J0R2ZtQ1NSVU5KWENyWUZnCmNpcXRUdjl3RGRnaGZSdUlrOERY
            Ni9VVGtFVUp6cEsveUFyZVlqa1BCbDAKLS0tIFA4aE1HL1R2ZW1VNFBsdThMK1pw
            MEh2S0RWeDRJM0JKSUNVMlJzQWRNUDAKj9PYPVPtQ3rG+rDThHMw43uyLcC0bTtB
            KlZ7cRSkUqVh0o/BdrD7m5ld8ItdRQkvaWGo3lg5y/Q1k9AYWdmPVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T08:52:37Z"
    mac: ENC[AES256_GCM,data:mRx3sFZ9yPAZ6tDb11pOyxWNGwOx8ZeIC+VnS+HusOJyE+qNunghQjRiudlxpM7ZyEIy390Z9SL4hNBYp8EXAFT5MHYxzQ6z7ayLnKKFbpeJ8JcNEkUd0T01/mM1opkrU8SE4zV5yrqRr3Sf/tyMFFadJlN4AmGay10kSuMQTHs=,iv:MTlANT/w7Eywf6TG5rEmt6r//j2Up26n+UzKTQ6VeMY=,tag:WlAQhWeM5ocstM9txPqsnw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
