apiVersion: v1
kind: Service
metadata:
  name: yamtrack
spec:
  type: LoadBalancer # You can patch this in an overlay
  selector:
    app: yamtrack
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
