apiVersion: v1
kind: Secret
metadata:
    name: karakeep-secret
    namespace: karakeep
type: Opaque
stringData:
    NEXTAUTH_URL: ENC[AES256_GCM,data:tZlGENYO2QLbFPVaYH1e5jxEqEUUvBvgvt9xoJo=,iv:z3euGslVIclvyKZoCZzqHjZDmc5/WHc3GHW1M/VJjaU=,tag:W4VVJfIbUydQy/3rOKQjqA==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:wPQhZA+AWtXXe6foGh33RajcPrnPKZ2aH+6HjdaAJWtIx6t7KTHzdCUDxcOcKbp8,iv:tUlLlimMNrhI9wgKz9Z6EQuDdqunx4u7W4Cr2GmE24Q=,tag:iXOjRB/wAbt7F4simXfo8w==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:+Zimxq62x+mnzkEQIoj7Nz7DeCpyzwHEP4PNhYBgC0lpNwNMnWoaUFY/bOp7/Y0F,iv:Vh6O6637MRJiD9J6WzpjfXseKxGTql4iQn7Iup7DBGo=,tag:bKUYP9zHWTDbOR924FIXPQ==,type:str]
    NEXT_PUBLIC_SECRET: ENC[AES256_GCM,data:iKxPZDg4J85/HEX341ml8LuQWYSvYzI//dmoofYuUSaLc0uS9U/6kYGDWbyD+Y4n,iv:0iUZoSiX3UC5I2s5fCEWZVLZJ5kwsfn7az6qfFF3wHw=,tag:4ROMBoaP5hiAdw9fTim2SA==,type:str]
sops:
    age:
        - recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybGluWEgrd3VIQU94MjNK
            bHlIMVl4eUJjbWxhOXVidmRzcHkwOUhhTUdJCmhQVUJ0aVJvb0wxUGw3Q1RmNlgw
            NTBabjRGZzZjU1dNMDR0dGpGeUJ1ZzgKLS0tIEN3eWtaUWxvTkNSQlZ0MWVXdUgr
            NHBDWHJwQ25BSmpRckNObCtReXBHbk0KlWBqiQMesz+8I+GwCdUOI5xvPCMVw7Y5
            u2rarBnK2vxOMIyzYJ6QJHKYFj63bsRT3TDhLFmp4P/tfK9yOv9WNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T10:51:20Z"
    mac: ENC[AES256_GCM,data:a9MzMmisjGXildckrn72NgcKjMJvgTbAIeBAeFcAundWZ0sTZvvHcDg8m9rwmFD1TrE5Igpc6/EacW0/jHf5A3pRNzV55Xacd/lJPhb7PI5lFN/wZQPBJUBDgjWvI4UsZAM/k8DCKU3647Hpa3eLPFL5HPizxiLWpf0vc7dx4yg=,iv:Az2Dr+gf1jP/BudMfnyXd1nDX7mFkCy5vyH2pQEu63A=,tag:BzkvLgQZPSXRp+POf73mAA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
