apiVersion: v1
kind: Secret
metadata:
    name: karakeep-secret
    namespace: karakeep
type: Opaque
stringData:
    NEXTAUTH_URL: ENC[AES256_GCM,data:+taBAcf46DRwkZpBasd9tR61IKeH,iv:pXs4O/tjVlp5N20JRjM3VxwVmhzRzSuOlkzUd9QAgXo=,tag:JeZlAPrOehTL8MIXkl7U4A==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:wPQhZA+AWtXXe6foGh33RajcPrnPKZ2aH+6HjdaAJWtIx6t7KTHzdCUDxcOcKbp8,iv:tUlLlimMNrhI9wgKz9Z6EQuDdqunx4u7W4Cr2GmE24Q=,tag:iXOjRB/wAbt7F4simXfo8w==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:+Zimxq62x+mnzkEQIoj7Nz7DeCpyzwHEP4PNhYBgC0lpNwNMnWoaUFY/bOp7/Y0F,iv:Vh6O6637MRJiD9J6WzpjfXseKxGTql4iQn7Iup7DBGo=,tag:bKUYP9zHWTDbOR924FIXPQ==,type:str]
    NEXT_PUBLIC_SECRET: ENC[AES256_GCM,data:iKxPZDg4J85/HEX341ml8LuQWYSvYzI//dmoofYuUSaLc0uS9U/6kYGDWbyD+Y4n,iv:0iUZoSiX3UC5I2s5fCEWZVLZJ5kwsfn7az6qfFF3wHw=,tag:4ROMBoaP5hiAdw9fTim2SA==,type:str]
sops:
    age:
        - recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybGluWEgrd3VIQU94MjNK
            bHlIMVl4eUJjbWxhOXVidmRzcHkwOUhhTUdJCmhQVUJ0aVJvb0wxUGw3Q1RmNlgw
            NTBabjRGZzZjU1dNMDR0dGpGeUJ1ZzgKLS0tIEN3eWtaUWxvTkNSQlZ0MWVXdUgr
            NHBDWHJwQ25BSmpRckNObCtReXBHbk0KlWBqiQMesz+8I+GwCdUOI5xvPCMVw7Y5
            u2rarBnK2vxOMIyzYJ6QJHKYFj63bsRT3TDhLFmp4P/tfK9yOv9WNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T21:19:52Z"
    mac: ENC[AES256_GCM,data:Uu5zM2vTH0F4oj58iXok2DLpYdYR93BIiA6C65rCkR9GB8GofkKCxLhjO+a7yuZoo6Zb9QmgmoMGKBM1rDwlKQtWwNJfELk2zTSsBrREv70DIdNIa0gNXK+zrlioQnc5Gd/2k/s8+O6hHLQWQp0G3xdBhSwNrxB6QHsaDwQfs3U=,iv:mJTfiH7hT86GP/EgjXoMC4vahxz4GVOWdrsdnXP6y7o=,tag:lC6h5hNU21RAPT9SFPHe5A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
