apiVersion: v1
kind: Secret
metadata:
    name: s3-backup-hetzner-karakeep
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:0J46nyWRzD92MWB118BBW0ZnD3nzZwH88oXjPw9QL/9D2uNkokJInOqqKYtVVvuwhy672dcYDDO2jFGF9E3bmho1F0Yq9oQgQHXgPU8=,iv:cshtpOPe0Z58r4aVJo+hBAIjmlvu5dfM6wh8p5vmpM0=,tag:j6+WBV5pskc5LGeeCRMUhg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:wOEWdt+3WWGBg039tW4KmBotyuImRU6EN2Pd+82/ZJbvG157+JKvv5OHqQM=,iv:8SmV/domMxyQMMQy/kne0GWxxMlKrE62ogBKtWFhcOc=,tag:yV9rgwbp1Uql6Pl6plMyhA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:EmYzvRpV6bfY4As89eS1OXXbxh4=,iv:v4dZ1uFu7TG0Nh37Xwvl6JJ+QJYlk4hQ5U+E/t5yGM4=,tag:xlFYuAyaCi9ySXGYW21t3g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:TnGGrmed2L7YYViGX2lATB+4RJiWvFwJoNmXSKLhqj2WXii8JY/D4g==,iv:h6oAyF0nHLPuoj7TemFk8kIv3k3CfxhJATtPZMiaiyU=,tag:DqZuM8OV6esXsmYFl/B8Zw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdDV5cS9NUmQ3Q3BNVFpL
            endqcnBnR2Q0MWMvRUowU0JFbEh5eEZyczFZCldIMXp2K1hWU0tMK3BNVjFpSU01
            ZDFzQzRqZ3lOQWZuNS8rR3A2RGwrTFUKLS0tIDJUVHkvc2FHUlVTanV4eExuYXo1
            RDNYZStydU03WlhvQVlOaHdqLzl3N0EKq2hVEXy56sKWnCGExcfogNwKBqywhgAU
            V32jukaDC/oKuAM2xMdnGFDmPGkMOk40qraP75dgzMgR5S0H0fjfwg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T10:18:16Z"
    mac: ENC[AES256_GCM,data:0oWkjT6DahHQbpZi+VDlp7oFiw2oZ55ucdRlUNrBytISQGZO6AXQ70nUh8LD7s+idNwM5IcGOMgghXaknMLlFX8w6Y58/347Ju2qU80H8FPcjyy+pQhGP05VX0smGZkYFd6PXuUuTg9BiQRi2ZRKhp/Yr1Xno43ZrFQx6+xO3L0=,iv:+WWxgavqYKerlFSvTWAxaUybDLUkwSMFoMQvWYk7+gk=,tag:qOBX7pGmeTUUsbZ0KxkzzA==,type:str]
    version: 3.13.2
