apiVersion: v1
kind: Secret
metadata:
    name: s3-backup-hetzner-karakeep
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:0J46nyWRzD92MWB118BBW0ZnD3nzZwH88oXjPw9QL/9D2uNkokJInOqqKYtVVvuwhy672dcYDDO2jFGF9E3bmho1F0Yq9oQgQHXgPU8=,iv:cshtpOPe0Z58r4aVJo+hBAIjmlvu5dfM6wh8p5vmpM0=,tag:j6+WBV5pskc5LGeeCRMUhg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:wOEWdt+3WWGBg039tW4KmBotyuImRU6EN2Pd+82/ZJbvG157+JKvv5OHqQM=,iv:8SmV/domMxyQMMQy/kne0GWxxMlKrE62ogBKtWFhcOc=,tag:yV9rgwbp1Uql6Pl6plMyhA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:qjNMjrat9I5dTHX2YioKFdeBhBc=,iv:8ljlXYJl7lwzdBBY+LXJhB508Daq3RN8ginyuV4Bzg4=,tag:nwP5/UGnJqwL9sRfsnIqyw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:mJHaCOUrz2dCnAPxKYXcBJ6W+mo/sdTgErIo9eWo0z1M923yRImLiw==,iv:xY5/7uXojf1Fl5J+D7lBDYvt3Ow7xbHIYl0e+ifV9LQ=,tag:UTqdRx9fs9Um6MtqktPaAA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdDV5cS9NUmQ3Q3BNVFpL
            endqcnBnR2Q0MWMvRUowU0JFbEh5eEZyczFZCldIMXp2K1hWU0tMK3BNVjFpSU01
            ZDFzQzRqZ3lOQWZuNS8rR3A2RGwrTFUKLS0tIDJUVHkvc2FHUlVTanV4eExuYXo1
            RDNYZStydU03WlhvQVlOaHdqLzl3N0EKq2hVEXy56sKWnCGExcfogNwKBqywhgAU
            V32jukaDC/oKuAM2xMdnGFDmPGkMOk40qraP75dgzMgR5S0H0fjfwg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T10:44:29Z"
    mac: ENC[AES256_GCM,data:8iJeYE4ZvZBO77cgBsPI6tOsKh5F2oQGd6R8cxzKX2xlOjqwcea4mMCAaJXibPWFOr+mmK+uK1DYvSJ1K1RY0C96mPQ2kc6kG29ybfpx7bDmRUMtDFh/s6maz9s7CJVxFvANqyPdOta3PlKcsNe4E3O2QMeGXz/limeIhnlWdGk=,iv:R2ICLvatHUvkvyLik3eKoughsRGoeaenXISEElfLVzU=,tag:DFZfMREI0A6Dp1nydbTdvw==,type:str]
    version: 3.13.2
