apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: openbao-secret-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - openbao-unseal-keys.sops.yaml
  - openbao-static-unseal.sops.yaml
  - snapshot-s3-secret.sops.yaml
