# ============================================================
# NEVER commit this file without SOPS encryption.
# Workflow:
#   1. Replace all PLACEHOLDER values with real output from init-and-unseal.sh
#   2. sops --encrypt --in-place openbao-unseal-keys.sops.yaml
#   3. git add openbao-unseal-keys.sops.yaml && git commit
#   Never reverse steps 2 and 3.
# ============================================================
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: openbao-unseal-keys
    namespace: openbao
    labels:
        app.kubernetes.io/managed-by: sops
    annotations:
        openbao.cyberhawk.no/note: Revoke root-token after bootstrap. Keys for emergency manual unseal only.
stringData:
    unseal-key-1: ENC[AES256_GCM,data:yUYeR9LzKrXXO78nn7gETRLf9lOSvp6d+Ow2mERrAH76TbJUEQHNeE/4qFM=,iv:bYa8fUDW1H2EuGAEfPEri5AVZNCMVREr8HOai6IDQ6Y=,tag:GcIbBsLGaAECH0M/9BS7Hg==,type:str]
    unseal-key-2: ENC[AES256_GCM,data:IDJxVEJ7r5xOUl5pLlPYSdhDIxEJ7ErbmITFFvBSL1ctrwx5IoIBng6Qynk=,iv:F6l74XkY1MlbKx7pIvErUc0ZpkpNvr/DGgiHEuS/rCI=,tag:kdIW3XFms0P3zByw9te/gA==,type:str]
    unseal-key-3: ENC[AES256_GCM,data:jzGV0DJewMpwpoO5vzokyR/NoX/1IFopei/M50rWHYdd0zXVOMdAE0Wc1YQ=,iv:3H9rjUeU8nAZ7snLtfdpE3s3V4+59u6UT+g7HDZ/D00=,tag:UO8WTVAixWJL7a3vIqwxOA==,type:str]
    root-token: ENC[AES256_GCM,data:yoG7e5VhLRML0A6wc7wtjSPAeAPlaTa5WVA=,iv:Op1Zuh/pUxR0PCgYBAWvslKZ0tXL97WcUaARH/8aj2g=,tag:SYSffURfhSeEPGYUZlJaPQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4SjNlaGhUVEpoUzV6V3Vp
            VmVCTVptd2ZRZ3F0c2lVK29zczBLczlRN0NJCjYzVzVYcUFHR01TcE4xZmJlR3R3
            Y1BzYnZEUTJaNU9sU3lSWWNpQVVmWHMKLS0tIG9GcEZWbWNhSmJuK2k2T0NTOTB1
            MU50NHFqZGhGaWdpenhrZ2toZmxybkkK4fSw0a6L+FPqdOI1XrnJC2KoCVFrIM33
            5hcZLXNwdd5SxSUlws1kELxkl69lVK/4eT+akZ/FPQ5nMm77oZ9dZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-16T10:37:46Z"
    mac: ENC[AES256_GCM,data:T34ESqEzMQIsuL+3S5+bjMVIqnLAFt65PIQW6OSO6INCx3GGlwi91Bio6QRxrfbN84ebkWRfIMIULa1ujScJI9uhPHvt/hCjp1g/5lMD+Igu+CSw1DowV14y4JHct2lvD+tzVmLMuPC7Ro7i1N+1Nz0yllaUn2AdBay7L3TYv7A=,iv:smAg1rLW8VJ8XmYdvc4G7+OD+0LJc4f8IrONSrHxMvU=,tag:CnCJa7SipSn63lp/mjXm/A==,type:str]
    version: 3.13.0
