global:
  enabled: true
  tlsDisable: true

server:
  image:
    registry: "quay.io"
    repository: "openbao/openbao"
    tag: ""

  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
      setNodeId: true
      config: |
        ui = true

        listener "tcp" {
          tls_disable = 1
          address         = "[::]:8200"
          cluster_address = "[::]:8201"
        }

        storage "raft" {
          path = "/openbao/data"
        }

        service_registration "kubernetes" {}

  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi

  securityContext:
    capabilities:
      add:
        - IPC_LOCK

  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: democratic-csi-iscsi

  auditStorage:
    enabled: true
    size: 5Gi
    storageClass: democratic-csi-iscsi

  serviceAccount:
    create: true
    name: openbao

injector:
  enabled: true
  replicas: 1

ui:
  enabled: true
  serviceType: ClusterIP
