apiVersion: v1
kind: Secret
metadata:
    name: s3-backup-hetzner-openbao
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:DEm4koG7HtKXsVxnw3Wa6Rk2+yOIp2JdbN6RDaBN7K4NsJeF2LVwH6waMG9XR173z2g9Cw7SCcIh67n6D2BY,iv:KLmRBpG/XdMk4YsWzyHlfnIhnWKPizFEwoVcfBrxxyc=,tag:Ye5ieOx428RkxyHLOX5h0w==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:+WezOIB15V/lDAI/c3CpGLWIzU80t8wlUNaOgkCFBBBgUIgO3iyybZS5GNs=,iv:qUVDnAQJ4rACJaOSrUC/sDv7wVri/fPZiXCNbn4UeTc=,tag:MhxpIWpSWFkX1fj+fySQCg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:fV+xnY7jW8/XygIKLWXsaNIptuE=,iv:RenvNrVXEisEh6vL3MNforSIV0IuVvuBhsaMgQ8GHYY=,tag:ov0zc+CiKKFQNHpxuMy5gQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:lx0RAbDV7ZJndbYzkYvqzP2nF9a+gDoqXY7bOyZ5S5J+G43meFMtjg==,iv:gANCfqh+MbrUlQAaSwttJMbTb8gXuK7oKhQGDppBnxQ=,tag:fwtQ32h5XNX1ap4w1opaFA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZkY5TmJJS0tUY212Z0FM
            QlM0Zld3QWYrWitpYVo2SnY2YXRERVBFZkQ4CiszeEVUR3lySXEzRGJBemJsWUwy
            bWIwWS8vbW9UWHNTbDdGaXF1Z0F2WTAKLS0tIEwzUGNVbU9oenovQXpkK2h5T1Nk
            ck1VcGZzZi9mZTdoYlBKRHdzVm9aUmMKRdAcf7G0Kd3L6Kv0j0st2+obnre7OGNx
            apdffy1V9tVK6mkn6Elzd5GGgkrve5atIDW431KllEPPFNhOgxmZpQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T10:27:55Z"
    mac: ENC[AES256_GCM,data:lWeekd+M8XSnNqAZMKp6joW6/qaJlU3mWDOxiRNaUB77AuLHxTQiyYM17mIVxFle6D4qKvyQc61HPaMrKOnjmT72jk1Vs8NP8tuosffmxFwhOeMth2ekTfPVrEL4FZTfzv1ZNSHfq6v72iqdFpRX76PV1Fe+n6fHoYjOYEUUjVo=,iv:BCwtngdKiLCrSB25iB7l6TqgNMh/G13mTKRQGwBRxCI=,tag:IeM+GjXwwAK/NgAJHbhuIw==,type:str]
    version: 3.13.2
