apiVersion: v1
kind: Secret
metadata:
    name: s3-backup-hetzner-openbao
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:DEm4koG7HtKXsVxnw3Wa6Rk2+yOIp2JdbN6RDaBN7K4NsJeF2LVwH6waMG9XR173z2g9Cw7SCcIh67n6D2BY,iv:KLmRBpG/XdMk4YsWzyHlfnIhnWKPizFEwoVcfBrxxyc=,tag:Ye5ieOx428RkxyHLOX5h0w==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:+WezOIB15V/lDAI/c3CpGLWIzU80t8wlUNaOgkCFBBBgUIgO3iyybZS5GNs=,iv:qUVDnAQJ4rACJaOSrUC/sDv7wVri/fPZiXCNbn4UeTc=,tag:MhxpIWpSWFkX1fj+fySQCg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:A6E8FcfVSMp0LqM1wPHIsXeV2Zk=,iv:wd+3arO/8vIcqRmS7Ubo52RYWRB8MsJaXylIhMqbpiU=,tag:tu0WMX4Mzllycw7fTyUa8g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:dUW8Nw+6nLXirxQcXcFXHE5Uep+oAz6Btf0RAW6GVSAB/vJac9FREQ==,iv:RpPTeaIUkfJ3FbCZIiJdjatVC2+4gxq18bp8kMjBfOw=,tag:+HtEmUr4ytRCinrgrc+Jsg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZkY5TmJJS0tUY212Z0FM
            QlM0Zld3QWYrWitpYVo2SnY2YXRERVBFZkQ4CiszeEVUR3lySXEzRGJBemJsWUwy
            bWIwWS8vbW9UWHNTbDdGaXF1Z0F2WTAKLS0tIEwzUGNVbU9oenovQXpkK2h5T1Nk
            ck1VcGZzZi9mZTdoYlBKRHdzVm9aUmMKRdAcf7G0Kd3L6Kv0j0st2+obnre7OGNx
            apdffy1V9tVK6mkn6Elzd5GGgkrve5atIDW431KllEPPFNhOgxmZpQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T10:44:29Z"
    mac: ENC[AES256_GCM,data:OsH5ui/ro9IffkoKKBPyYhnilluGHm5/VoOWkLzsmIbt0xMCCn/qMHrZl/wV5IjMvFvvf14xq2LH4oB1WsXwsBxLA2EgdK0/hkdUsdBBk5/auxE2Z/s0qMEgH1IHO8XzTVFJq85mlq0QIO3Zh18bChvDELIO0eZhDrcTFKUishc=,iv:rDNBdlGL9+djdskBH5X2PJ9NmX1pmQbG60udIykzJ9o=,tag:m6ArvKTfHoccPPi4HPdL/A==,type:str]
    version: 3.13.2
