apiVersion: v1
kind: Secret
metadata:
    name: pdns-api-key
    namespace: pdns
stringData:
    PDNS_AUTH_API_KEY: ENC[AES256_GCM,data:ueHMpunKkWqTJQB06VDneNnlQ8a4kQsUNpUpzoavoKn4Rqc+e/K7He5FknhYKqct,iv:8r8/Hq2Tl+q8NSN3j+DSuSXXgVOPmil1kcBRlwcJPOM=,tag:dOhMySYUVg0m3azoXQ2+uw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Vy9mMTVrSWRiZHVQUFVV
            Q1pLZStRb2M5YWVoaWNnZXAveEluSExUdUJzClJWUWpEUzB5UUtjMGVPdDJhUDNK
            Z09iNitoTHVtL1BtWkpCV2srbk52c1UKLS0tIDdZMmZjL09kUjZDcXk4Q2ZLUjJH
            TjJ6dkVEdHpEY1FGTjNXTnRVeVdOVjgKxPu1kZtW4ZnN7qaGgBEDV6PLHTe8pzoJ
            QgHQjSUr9TtZ/hv+JufNGJGoEhpx/7MuiGusbjvxq8DpIiQ5Yrsc1w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age102rv5x9lk7d694qlelkx8j8yxxtx20vfymkx042xgenqdw2ytyssr83usk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-19T13:06:21Z"
    mac: ENC[AES256_GCM,data:8oju49imAHg7BaJmpkRL3ffczTBYWRXVPs+BuNGcckaFNrbnU8idaPbJIBhSpIM7gLBRBmMB6HzhEkMkx32Fzy+d+Zx1XEf72FKNMU8GQUx85NzgDCQ3jaCDAt0gCaobceUl5QxsUFDTA8Mfj0dte7c/5LSbd+Dt1v6zGas/bas=,iv:PlgfakcxCVOLbVUVN9+O6hyWzBsP77SjZK/vBu5gc+s=,tag:Jr+SOxewCBNAjIAbY1OdWA==,type:str]
    version: 3.13.2
